- type: entity
  parent: TrashMimanaPeel
  id: MimanaPeelStealthy
  name: "шкірка мімани"
  suffix: Stealthy
  components:
  - type: Stealth
    maxVisibility: 1
  - type: StealthOnMove
    passiveVisibilityRate: -0.5
    movementVisibilityRate: 0.6
