/*
 * This file is sublicensed under MIT License
 * https://github.com/space-wizards/space-station-14/blob/master/LICENSE.TXT
 */

using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Planets.Shields;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FarHorizons.Planets.Shields;

/// <summary>
/// Read-only status readout for the planetary shield generator: cycle stage, grid draw,
/// time to the next lifecycle event and the charge buffer. There's no power switch —
/// the generator just runs.
/// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CEShieldGeneratorWindow : FancyWindow
    {
        /// <summary>Raised with the requested master-switch state when the toggle is pressed.</summary>
        public Action<bool>? OnTogglePressed;

        /// <summary>Last known master-switch state, so the toggle button flips the right way.</summary>
        private bool _enabled = true;

        public CEShieldGeneratorWindow()
        {
            RobustXamlLoader.Load(this);

            Title = Loc.GetString("ce-shield-generator-window-title");

            ToggleButton.OnPressed += _ => OnTogglePressed?.Invoke(!_enabled);
        }

        public void SetEntity(EntityUid uid)
        {
            EntityView.SetEntity(uid);
        }

        public void UpdateState(CEShieldGeneratorBuiState state)
        {
            _enabled = state.Enabled;

            // The master switch is dead when the generator isn't on a planet at all.
            ToggleButton.Disabled = !state.OnPlanet;
            ToggleButton.Text = Loc.GetString(state.Enabled
                ? "ce-shield-generator-window-disable"
                : "ce-shield-generator-window-enable");
        // Off-planet overrides the whole cycle readout: the generator is inert, not
        // merely waiting on power.
        var (statusLoc, statusStyle) = !state.OnPlanet
            ? ("ce-shield-generator-window-status-no-planet", "Danger")
            : state.Stage switch
            {
                CEShieldGeneratorStage.Charging => ("ce-shield-generator-window-status-charging", "Caution"),
                CEShieldGeneratorStage.SpinningUp => ("ce-shield-generator-window-status-spinning-up", "Caution"),
                CEShieldGeneratorStage.Active => ("ce-shield-generator-window-status-active", "Good"),
                CEShieldGeneratorStage.Cooldown => ("ce-shield-generator-window-status-cooldown", "Danger"),
                _ => ("ce-shield-generator-window-status-cooldown", "Danger"),
            };
        StatusLabel.Text = Loc.GetString(statusLoc);
        StatusLabel.SetOnlyStyleClass(statusStyle);

        PowerLabel.Text = Loc.GetString("ce-shield-generator-window-power-value",
            ("received", FormatPower(state.ReceivedPower)),
            ("wanted", FormatPower(state.WantedPower)));
        PowerLabel.SetOnlyStyleClass(
            state.WantedPower <= 0f
                ? "Disabled"
                : MathHelper.CloseToPercent(state.ReceivedPower, state.WantedPower, 0.01f) ? "Good" : "Caution");

        EtaLabel.Text = state.EtaSeconds >= 0f
            ? Loc.GetString("ce-shield-generator-window-eta-value",
                ("left", TimeSpan.FromSeconds(Math.Min(state.EtaSeconds, 86_399f))))
            : Loc.GetString("ce-shield-generator-window-eta-none");
        EtaLabel.SetOnlyStyleClass(state.EtaSeconds >= 0f ? "Caution" : "Disabled");

        var fraction = state.MaxCharge > 0f ? state.Charge / state.MaxCharge : 0f;
        ChargeBar.Value = fraction;
        ChargeText.Text = fraction.ToString("P0");
    }

    /// <summary>2 GW doesn't fit the usual watt labels; scale to a sane SI prefix.</summary>
    private static string FormatPower(float watts) => watts switch
    {
        >= 1e9f => $"{watts / 1e9f:F1} GW",
        >= 1e6f => $"{watts / 1e6f:F1} MW",
        >= 1e3f => $"{watts / 1e3f:F1} kW",
        _ => $"{watts:F0} W",
    };
}
