// SPDX-FileCopyrightText: 2025 Coenx-flex
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Pirate.CorticalBorer;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.CorticalBorer;

[GenerateTypedNameReferences]
public sealed partial class CorticalBorerReagentCardControl : Control
{
    public Action<string>? OnPressed;

    public CorticalBorerReagentCardControl(CorticalBorerDispenserItem chemical)
    {
        RobustXamlLoader.Load(this);

        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = chemical.ReagentColor };
        ReagentNameLabel.Text = chemical.ReagentName;
        FillLabel.Text = Loc.GetString("cortical-borer-dispenser-window-cost",
            ("cost", chemical.Cost * chemical.Amount));
        MainButton.Disabled = chemical.Chems < chemical.Cost * chemical.Amount;
        MainButton.OnPressed += _ => OnPressed?.Invoke(chemical.ReagentId);
    }
}
