// SPDX-FileCopyrightText: 2025 Coenx-flex
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._Pirate.CorticalBorer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.CorticalBorer;

[GenerateTypedNameReferences]
public sealed partial class CorticalBorerDispenserWindow : FancyWindow
{
    public event Action<string>? OnDispenseReagentButtonPressed;

    public CorticalBorerDispenserWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(CorticalBorerDispenserBoundUserInterfaceState state)
    {
        UpdateReagentsList(state.DisList);
        AmountGrid.Selected = state.SelectedDispenseAmount.ToString();
    }

    private void UpdateReagentsList(List<CorticalBorerDispenserItem> chemicals)
    {
        ReagentList.Children.Clear();
        chemicals.Sort((left, right) => left.ReagentName.CompareTo(right.ReagentName));

        foreach (var chemical in chemicals)
        {
            var card = new CorticalBorerReagentCardControl(chemical);
            card.OnPressed += OnDispenseReagentButtonPressed;
            ReagentList.Children.Add(card);
        }
    }
}
