// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls; // Pirate - DeltaV surgery UI
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Shitmed.Medical.Surgery;

[GenerateTypedNameReferences]
// Pirate - DeltaV surgery UI
public sealed partial class SurgeryWindow : FancyWindow
{
    public IReadOnlyList<TextureButton> BodyPartButtons { get; }

    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);

        // Pirate - Persistent buttons are rebound to the current body parts by SurgeryBui.
        BodyPartButtons =
        [
            ChestButton,
            HeadButton,
            LArmButton,
            LHandButton,
            RArmButton,
            RHandButton,
            LLegButton,
            LFootButton,
            RLegButton,
            RFootButton,
            CarpButton,
        ];
    }
}
