# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: HecuOperative
  name: job-name-hecu
  description: job-description-hecu
  playTimeTracker: JobHecuOperative
  # Pirate: HECU rework start
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipERT
  # Pirate: HECU rework end
  setPreference: false
  startingGear: HECUOperativeGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer

- type: startingGear
  id: HECUOperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHECUUrbanCamo # Pirate: HECU rework
    back: ClothingBackpackHECUFilled # Pirate: HECU rework
    mask: ClothingMaskGasHECU # Pirate: HECU rework
    eyes: ClothingEyesGlassesMedSec
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorHECU # Pirate: HECU rework
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetHECUPoweredNVG # Pirate: HECU rework
    id: HecuPDA
    belt: ClothingBeltHECUFilled # Pirate: HECU rework
    pocket1: FlashlightSeclite # Pirate: HECU rework
    pocket2: PowerCellHigh # Pirate: HECU rework
  inhand:
  - WeaponRifleM16 # Pirate: HECU rework