// SPDX-FileCopyrightText: 2025 Starlight
// SPDX-FileCopyrightText: 2026 SpaceStationUA
// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Pirate.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterInfoEditor : Control
{
    public CharacterInfoEditor()
    {
        RobustXamlLoader.Load(this);

        var localization = IoCManager.Resolve<ILocalizationManager>();
        SetPlaceholder(PhysicalDescriptionInput, "character-info-editor-physical-placeholder", localization);
        SetPlaceholder(PersonalityDescriptionInput, "character-info-editor-personality-placeholder", localization);
        SetPlaceholder(ExploitableInfoInput, "character-info-editor-exploitable-placeholder", localization);
        SetPlaceholder(SecretsInput, "character-info-editor-secrets-placeholder", localization);
    }

    private static void SetPlaceholder(TextEdit control, string locId, ILocalizationManager localization)
    {
        control.Placeholder = new Rope.Leaf(localization.GetString(locId));
    }
}
