// SPDX-FileCopyrightText: 2025 Starlight
// SPDX-FileCopyrightText: 2026 SpaceStationUA
// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Pirate.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class OOCInfoEditor : Control
{
    public OOCInfoEditor()
    {
        RobustXamlLoader.Load(this);

        var localization = IoCManager.Resolve<ILocalizationManager>();
        SetPlaceholder(PersonalNotesInput, "character-info-editor-personal-notes-placeholder", localization);
        SetPlaceholder(OOCNotesInput, "character-info-editor-ooc-notes-placeholder", localization);
    }

    private static void SetPlaceholder(TextEdit control, string locId, ILocalizationManager localization)
    {
        control.Placeholder = new Rope.Leaf(localization.GetString(locId));
    }
}
