using Content.Client.UserInterface.Controls;
using Content.Shared._MACRO.StrangeMoods;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization.Manager;

namespace Content.Client._MACRO.StrangeMoods;

[GenerateTypedNameReferences]
public sealed partial class StrangeMoodInitUi : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private ISerializationManager _serialization = default!;

    public event Action<StrangeMoodDefinition>? OnPresetAccepted;

    private List<StrangeMoodDefinition> _definitions = [];

    public StrangeMoodInitUi()
    {
        RobustXamlLoader.Load(this);
        MoodPresetDropDown.OnItemSelected += args => MoodPresetDropDown.SelectId(args.Id);
        AcceptPresetButton.OnPressed += _ => AcceptPreset();

        var definitions = _proto.EnumeratePrototypes<StrangeMoodDefinitionPrototype>();
        var i = 0;
        foreach (var proto in definitions)
        {
            MoodPresetDropDown.AddItem(proto.Name, i);

            // Pirate: prototype copiers require prototype targets; send only independent runtime mood data.
            var def = new StrangeMoodDefinition
            {
                ProtoId = proto.ProtoId,
                SharedMoodPrototype = proto.SharedMoodPrototype,
                Datasets = _serialization.CreateCopy(proto.Datasets, notNullableOverride: true),
                Moods = _serialization.CreateCopy(proto.Moods, notNullableOverride: true),
                MoodsChangedMessage = proto.MoodsChangedMessage,
                MoodsChangedSound = _serialization.CreateCopy(proto.MoodsChangedSound),
                MoodsChangedColor = proto.MoodsChangedColor,
                ActionViewMoods = proto.ActionViewMoods,
            };
            _definitions.Insert(i++, def);
        }
    }

    private void AcceptPreset()
    {
        var id = MoodPresetDropDown.SelectedId;
        var def = _definitions[id];
        OnPresetAccepted?.Invoke(def);
    }
}
