// SPDX-FileCopyrightText: 2026 CyberLanos <cyber.lanos00@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Shared._Pirate.Paper;
using Content.Shared.Tag;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Pirate.Paper;

/// <summary>
/// Pirate: the cover picker, laid out like the agent ID card menu - a search box over a
/// grid of buttons, each showing the sprite of the book whose cover it would put on.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class BookSkinWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IComponentFactory _compFactory = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystems = default!;

    private readonly SpriteSystem _sprite;
    private readonly TagSystem _tag;

    /// <summary>Fired with the cover the player picked.</summary>
    public event Action<EntProtoId>? OnCoverSelected;

    private readonly List<EntityPrototype> _looks = new();

    private string? _current;
    private string _filter = string.Empty;

    private const float CoverSize = 84f;

    public BookSkinWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entitySystems.GetEntitySystem<SpriteSystem>();
        _tag = _entitySystems.GetEntitySystem<TagSystem>();

        Search.OnTextChanged += args =>
        {
            _filter = args.Text;
            RebuildGrid();
        };
    }

    /// <summary>
    /// Fills the window with every cover the server would accept, highlighting the one
    /// the book is wearing right now.
    /// </summary>
    public void Populate(string? currentSkin, ProtoId<TagPrototype> sourceTag)
    {
        _looks.Clear();
        _looks.AddRange(BookSkinLooks.Get(_proto, _compFactory, _tag, sourceTag));

        _current = currentSkin;
        RebuildGrid();
    }

    private void RebuildGrid()
    {
        CoverGrid.RemoveAllChildren();

        var group = new ButtonGroup();

        foreach (var look in _looks)
        {
            if (!MatchesFilter(look))
                continue;

            var textures = _sprite.GetPrototypeTextures(look, out _)
                .Select(texture => texture.Default)
                .ToList();

            var button = new Button
            {
                Group = group,
                Pressed = string.Equals(look.ID, _current, StringComparison.Ordinal),
                ToolTip = look.Name,
                SetSize = new Vector2(CoverSize, CoverSize),
            };

            if (textures.Count > 0)
            {
                button.AddChild(new LayeredTextureRect
                {
                    Textures = textures,
                    TextureScale = new Vector2(1.5f, 1.5f),
                    HorizontalAlignment = Control.HAlignment.Center,
                    VerticalAlignment = Control.VAlignment.Center,
                });
            }
            else
            {
                button.AddChild(new Label { Text = look.Name });
            }

            var id = new EntProtoId(look.ID);
            button.OnPressed += _ => OnCoverSelected?.Invoke(id);
            CoverGrid.AddChild(button);
        }
    }

    private bool MatchesFilter(EntityPrototype look)
    {
        if (string.IsNullOrWhiteSpace(_filter))
            return true;

        return look.Name.Contains(_filter, StringComparison.CurrentCultureIgnoreCase);
    }
}
