using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Pirate.Shared.PAI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Pirate.Client.PAI;

[GenerateTypedNameReferences]
public sealed partial class PAIMedInjectorWindow : FancyWindow
{
    public event Action<string>? OnInject;

    private readonly Dictionary<string, (Button Button, Label Label)> _medEntries = new();
    private bool _hasCarrier = true;

    public PAIMedInjectorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(PAIMedInjectorBoundUserInterfaceState state)
    {
        CapacityBar.Value = state.MaxCapacity > 0 ? state.CurrentCapacity / state.MaxCapacity : 0;
        _hasCarrier = state.CarrierPresent;

        // Rebuild buttons if meds changed
        if (_medEntries.Count != state.Meds.Count)
        {
            MedsContainer.RemoveAllChildren();
            _medEntries.Clear();

            foreach (var med in state.Meds)
            {
                var container = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(0, 3) };

                var button = new Button
                {
                    Text = med.Name,
                    MinSize = new Vector2(0, 30),
                    ToolTip = med.Description,
                };

                var reasonLabel = new Label
                {
                    Text = "",
                    Visible = false,
                    FontColorOverride = Color.Gray,
                };

                var idCapture = med.Id;
                button.OnPressed += _ => OnInject?.Invoke(idCapture);

                container.AddChild(button);
                container.AddChild(reasonLabel);
                MedsContainer.AddChild(container);
                _medEntries[med.Id] = (button, reasonLabel);
            }
        }

        // Update button and reason states
        foreach (var med in state.Meds)
        {
            if (!_medEntries.TryGetValue(med.Id, out var entry))
                continue;

            var (button, reason) = entry;

            if (!_hasCarrier)
            {
                button.Text = med.Name;
                button.Disabled = true;
                reason.Text = Loc.GetString("pai-med-injector-no-carrier-reason");
                reason.Visible = true;
            }
            else if (!med.Available && med.CooldownRemaining <= 0)
            {
                button.Text = med.Name;
                button.Disabled = true;
                reason.Text = Loc.GetString("pai-med-injector-no-capacity-reason");
                reason.Visible = true;
            }
            else if (med.CooldownRemaining > 0)
            {
                button.Text = $"{med.Name} ({med.CooldownRemaining:F0}s)";
                button.Disabled = true;
                reason.Text = Loc.GetString("pai-med-injector-cooldown-reason", ("time", (int)med.CooldownRemaining));
                reason.Visible = true;
            }
            else
            {
                button.Text = med.Name;
                button.Disabled = false;
                reason.Visible = false;
            }
        }

        // Show overall status
        if (!_hasCarrier)
        {
            StatusLabel.Text = Loc.GetString("pai-med-injector-no-carrier");
            StatusLabel.Visible = true;
        }
        else
        {
            StatusLabel.Visible = false;
        }

        CapacityBar.Value = state.MaxCapacity > 0 ? state.CurrentCapacity / state.MaxCapacity : 0;
    }
}
