- type: department
  id: Interdyne
  name: department-Interdyne
  description: department-Interdyne-description
  color: "#2d650e"
  editorHidden: true
  roles:
  - CaptainInterdyne
  - InterdyneSecure
  - InterdyneEngineer
  - InterdyneDeputy
  - InterdyneService
  - Interdyne
  - InterdyneMed
  - InterdynePilot
  - InterdyneShaftMiners

- type: department
  id: Dday
  name: department-dday
  description: department-dday-description
  editorHidden: false
  color: "#2d650e"
  roles:
  - USAEfreitor
  - USALeutenant
  - GEREfreitor