- type: department
  id: Service
  name: department-Service
  description: department-Service-description
  color: "#9FED58"
  weight: -9
  roles:
  - HeadOfPersonnel
  - Bartender
  - Botanist
  - Chaplain
  - Chef
  - Janitor
  - Librarian
  - ServiceWorker

- type: department
  id: Interdyne
  name: department-Interdyne
  description: department-Interdyne-description
  color: "#2d650e"
  roles:
  - CaptainInterdyne
  - InterdyneSecure
  - InterdyneEngineer
  - InterdyneDeputy
  - InterdyneService
  - Interdyne
  - InterdyneMed
  - InterdynePilot
  - InterdyneShaftMiners
