// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Message;
using Content.Shared.Atmos;
using Content.Shared.Atmos.EntitySystems;
using Content.Shared.Atmos.Monitor;
using Content.Shared.Atmos.Prototypes;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Atmos.Monitor.UI.Widgets;

[GenerateTypedNameReferences]
public sealed partial class SensorInfo : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;

    public Action<string, AtmosMonitorThresholdType, AtmosAlarmThreshold, Gas?>? OnThresholdUpdate;
    public event Action<AtmosSensorData>? SensorDataCopied;
    private string _address;

    private ThresholdControl _pressureThreshold;
    private ThresholdControl _temperatureThreshold;
    private Dictionary<Gas, ThresholdControl> _gasThresholds = new();
    private Dictionary<Gas, RichTextLabel> _gasLabels = new();
    private Button _copySettings => CCopySettings;

    public SensorInfo(AtmosSensorData data, string address)
    {
        IoCManager.InjectDependencies(this);
        var atmosphereSystem = _entMan.System<SharedAtmosphereSystem>();

        RobustXamlLoader.Load(this);

        _address = address;

        SensorAddress.Title = Loc.GetString("air-alarm-ui-window-listing-title", ("address", _address), ("state", data.AlarmState));

        AlarmStateLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-alarm-state-indicator",
                    ("color", AirAlarmWindow.ColorForAlarm(data.AlarmState)),
                    ("state", data.AlarmState)));
        PressureLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-pressure-indicator",
                    ("color", AirAlarmWindow.ColorForThreshold(data.Pressure, data.PressureThreshold)),
                    ("pressure", $"{data.Pressure:0.##}")));
        TemperatureLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-temperature-indicator",
                ("color", AirAlarmWindow.ColorForThreshold(data.Temperature, data.TemperatureThreshold)),
                ("tempC", $"{TemperatureHelpers.KelvinToCelsius(data.Temperature):0.#}"),
                ("temperature", $"{data.Temperature:0.##}")));

        foreach (var (gas, amount) in data.Gases)
        {
            // Pirate: skip gases the server sent no threshold for (e.g. newly added HFR gases)
            // so we never throw on a missing dictionary key.
            if (!data.GasThresholds.TryGetValue(gas, out var gasThreshold))
                continue;

            var label = new RichTextLabel();

            var fractionGas = amount / data.TotalMoles;

            ProtoId<GasPrototype> gasProtoId = atmosphereSystem.GetGas(gas);
            var gasName = _prototypeManager.Index(gasProtoId).Name;

            label.SetMarkup(Loc.GetString("air-alarm-ui-gases-indicator",
                ("gas", Loc.GetString(gasName)),
                ("color", AirAlarmWindow.ColorForThreshold(fractionGas, gasThreshold)), // Pirate
                ("amount", $"{amount:0.####}"),
                ("percentage", $"{(100 * fractionGas):0.##}")));
            GasContainer.AddChild(label);
            _gasLabels.Add(gas, label);

            var gasThresholdControl = new ThresholdControl(Loc.GetString($"air-alarm-ui-thresholds-gas-title"), gasThreshold, AtmosMonitorThresholdType.Gas, gas, 100); // Pirate
            gasThresholdControl.Margin = new Thickness(20, 2, 2, 2);
            gasThresholdControl.ThresholdDataChanged += (type, alarmThreshold, arg3) =>
            {
                OnThresholdUpdate?.Invoke(_address, type, alarmThreshold, arg3);
            };

            _gasThresholds.Add(gas, gasThresholdControl);
            GasContainer.AddChild(gasThresholdControl);
        }

        _pressureThreshold = new ThresholdControl(Loc.GetString("air-alarm-ui-thresholds-pressure-title"), data.PressureThreshold, AtmosMonitorThresholdType.Pressure);
        PressureThresholdContainer.AddChild(_pressureThreshold);
        _temperatureThreshold = new ThresholdControl(Loc.GetString("air-alarm-ui-thresholds-temperature-title"),
            data.TemperatureThreshold,
            AtmosMonitorThresholdType.Temperature);
        TemperatureThresholdContainer.AddChild(_temperatureThreshold);

        _pressureThreshold.ThresholdDataChanged += (type, threshold, arg3) =>
        {
            OnThresholdUpdate?.Invoke(_address, type, threshold, arg3);
        };

        _temperatureThreshold.ThresholdDataChanged += (type, threshold, arg3) =>
        {
            OnThresholdUpdate?.Invoke(_address, type, threshold, arg3);
        };

        _copySettings.OnPressed += _ =>
        {
            SensorDataCopied?.Invoke(data);
        };
    }

    public void ChangeData(AtmosSensorData data)
    {
        IoCManager.InjectDependencies(this);
        var atmosphereSystem = _entMan.System<SharedAtmosphereSystem>();

        SensorAddress.Title = Loc.GetString("air-alarm-ui-window-listing-title", ("address", _address), ("state", data.AlarmState));

        AlarmStateLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-alarm-state-indicator",
                    ("color", AirAlarmWindow.ColorForAlarm(data.AlarmState)),
                    ("state", data.AlarmState)));

        PressureLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-pressure-indicator",
                    ("color", AirAlarmWindow.ColorForThreshold(data.Pressure, data.PressureThreshold)),
                    ("pressure", $"{data.Pressure:0.##}")));
        TemperatureLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-temperature-indicator",
                ("color", AirAlarmWindow.ColorForThreshold(data.Temperature, data.TemperatureThreshold)),
                ("tempC", $"{TemperatureHelpers.KelvinToCelsius(data.Temperature):0.#}"),
                ("temperature", $"{data.Temperature:0.##}")));

        foreach (var (gas, amount) in data.Gases)
        {
            if (!_gasLabels.TryGetValue(gas, out var label))
            {
                continue;
            }

            var fractionGas = amount / data.TotalMoles;

            ProtoId<GasPrototype> gasProtoId = atmosphereSystem.GetGas(gas);
            var gasName = _prototypeManager.Index(gasProtoId).Name;

            // Pirate: skip gases the server sent no threshold for (e.g. newly added HFR gases)
            // and hide the stale row so it doesn't keep showing the last known value.
            if (!data.GasThresholds.TryGetValue(gas, out var gasThreshold))
            {
                label.Visible = false;
                continue;
            }

            label.Visible = true;
            label.SetMarkup(Loc.GetString("air-alarm-ui-gases-indicator",
                ("gas", Loc.GetString(gasName)),
                ("color", AirAlarmWindow.ColorForThreshold(fractionGas, gasThreshold)), // Pirate
                ("amount", $"{amount:0.####}"),
                ("percentage", $"{(100 * fractionGas):0.##}")));
        }

        _pressureThreshold.UpdateThresholdData(data.PressureThreshold, data.Pressure);
        _temperatureThreshold.UpdateThresholdData(data.TemperatureThreshold, data.Temperature);
        foreach (var (gas, control) in _gasThresholds)
        {
            // Pirate: hide the control when the server no longer reports the gas or
            // its threshold, and never index data.Gases without checking the key first.
            if (!data.GasThresholds.TryGetValue(gas, out var threshold)
                || !data.Gases.TryGetValue(gas, out var amount))
            {
                control.Visible = false;
                continue;
            }

            control.Visible = true;
            control.UpdateThresholdData(threshold, amount / data.TotalMoles);
        }
    }

 }