using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Pirate.Client.LightPaint;

[GenerateTypedNameReferences]
public sealed partial class LightPaintWindow : FancyWindow
{
    /// <summary>
    ///     tgstation's crayon palette (COLOR_CRAYON_* in code/__DEFINES/colors.dm, plus the
    ///     white crayon), which is the full fixed set its spray can offers.
    /// </summary>
    private static readonly Color[] CrayonPresets =
    {
        Color.FromHex("#DA0000"), // red
        Color.FromHex("#FF9300"), // orange
        Color.FromHex("#FFF200"), // yellow
        Color.FromHex("#A8E61D"), // green
        Color.FromHex("#00B7EF"), // blue
        Color.FromHex("#DA00FF"), // purple
        Color.FromHex("#1C1C1C"), // black
        Color.White,
    };

    /// <summary>
    ///     The colours of this game's own crystal light tubes, so a painted bulb can be matched
    ///     exactly to one you could otherwise only get by finding the crystal variant.
    /// </summary>
    private static readonly Color[] BulbPresets =
    {
        Color.FromHex("#fb4747"), // red
        Color.FromHex("#ff8227"), // orange
        Color.FromHex("#ffde46"), // yellow
        Color.FromHex("#52ff39"), // green
        Color.FromHex("#47f8ff"), // cyan
        Color.FromHex("#39a1ff"), // blue
        Color.FromHex("#800080"), // deep purple
        Color.FromHex("#ff66cc"), // pink
    };

    // Traits-style UI kit (design/ss14-traits-style-kit.html): selection is an accent outline,
    // never a fill -- filling a swatch would hide the colour it is there to show.
    private static readonly Color Accent = Color.FromHex("#4f93d6");
    private static readonly Color LineSoft = Color.FromHex("#2b313d");

    private const int SwatchSize = 30;
    private const int SelectedBorder = 2;

    private readonly List<(StyleBoxFlat Border, Color Color)> _swatches = new();

    /// <summary>
    ///     Guards against the swatch rows and the sliders driving each other in a loop: setting
    ///     <see cref="ColorSelectorSliders.Color"/> pushes values into the sliders, which fires
    ///     their change event right back at us.
    /// </summary>
    private bool _updating;

    public event Action<Color>? OnColorSelected;

    public LightPaintWindow()
    {
        RobustXamlLoader.Load(this);

        Swatches.AddChild(BuildRow(CrayonPresets, topRow: true));
        Swatches.AddChild(BuildRow(BulbPresets, topRow: false));

        ColorSelector.OnColorChanged += OnPickerChanged;
    }

    private BoxContainer BuildRow(Color[] colors, bool topRow)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, topRow ? 4 : 0),
        };

        foreach (var color in colors)
        {
            // The swatch's own border doubles as the selection outline: transparent until picked.
            var border = new StyleBoxFlat
            {
                BackgroundColor = LineSoft,
                BorderColor = Accent,
                BorderThickness = new Thickness(0),
            };

            var swatch = color;
            var button = new Button
            {
                MinSize = new Vector2(SwatchSize, SwatchSize),
                ModulateSelfOverride = color,
            };
            button.OnPressed += _ => SelectColor(swatch, notify: true);

            var panel = new PanelContainer
            {
                PanelOverride = border,
                Margin = new Thickness(2, 0),
            };
            panel.AddChild(button);

            row.AddChild(panel);
            _swatches.Add((border, color));
        }

        return row;
    }

    private void OnPickerChanged(Color color)
    {
        if (_updating)
            return;

        UpdateSelection(color);
        OnColorSelected?.Invoke(color);
    }

    private void SelectColor(Color color, bool notify)
    {
        // Pushing the colour into the sliders re-raises OnColorChanged once per slider, so mute
        // ourselves and send a single message afterwards instead of one per channel.
        _updating = true;
        ColorSelector.Color = color;
        _updating = false;

        UpdateSelection(color);

        if (notify)
            OnColorSelected?.Invoke(color);
    }

    /// <summary>
    ///     Outlines the preset matching the current colour, so picking with the sliders keeps the
    ///     swatch rows in sync too.
    /// </summary>
    private void UpdateSelection(Color color)
    {
        foreach (var (border, swatch) in _swatches)
        {
            border.BorderThickness = new Thickness(Matches(swatch, color) ? SelectedBorder : 0);
        }
    }

    /// <summary>
    ///     Compares on 8-bit channels: round-tripping a colour through the HSV sliders does not
    ///     come back exactly equal to the hex it started from.
    /// </summary>
    private static bool Matches(Color a, Color b)
    {
        return a.RByte == b.RByte && a.GByte == b.GByte && a.BByte == b.BByte;
    }

    /// <summary>
    ///     Seeds the window from the can's current colour without echoing a message back to it.
    /// </summary>
    public void SetColor(Color color)
    {
        SelectColor(color, notify: false);
    }
}
