// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Stylesheets.Palette;
using Content.Client.UserInterface.Controls;
using Content.Shared._Pirate.Shuttles.Warp;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Pirate.Shuttles.Warp;

[GenerateTypedNameReferences]
public sealed partial class WarpDriveWindow : FancyWindow
{
    private WarpDriveBoundUserInterface? _bui;

    public WarpDriveWindow()
    {
        RobustXamlLoader.Load(this);

        ToggleButton.OnPressed += _ => _bui?.Toggle();
    }

    public void UpdateWindow(WarpDriveBoundUserInterface bui)
    {
        _bui = bui;
        EntityView.SetEntity(bui.Owner);
    }

    public void UpdateState(WarpDriveBuiState state)
    {
        StateLabel.Text = Loc.GetString(state.DriveState switch
        {
            WarpDriveState.Idle => "warp-drive-window-state-idle",
            WarpDriveState.Spooling => "warp-drive-window-state-spooling",
            WarpDriveState.Engaged => "warp-drive-window-state-engaged",
            WarpDriveState.InTransit => "warp-drive-window-state-in-transit",
            _ => throw new ArgumentOutOfRangeException()
        });

        // Colour carries the same information as the text here, because during a countdown nobody
        // is reading carefully - they glance at the window.
        StateLabel.FontColorOverride = state.DriveState switch
        {
            WarpDriveState.Idle => Palettes.Neutral.Base,
            WarpDriveState.Spooling => Palettes.Status.Warning,
            WarpDriveState.Engaged => Palettes.Status.Good,
            WarpDriveState.InTransit => Palettes.Status.Good,
            _ => Palettes.Neutral.Base
        };

        UpdatePower(state);
        UpdateRange(state);
        UpdateSpool(state);
        UpdateHeat(state);
        UpdateTimers(state);
        UpdateButton(state);
    }

    /// <summary>
    ///     Reports what the grid is supplying against what the drive is asking for. A shortfall is
    ///     the leading indicator of a drive about to drop, so it gets called out in text, not just
    ///     left for the crew to infer from two numbers not matching.
    /// </summary>
    private void UpdatePower(WarpDriveBuiState state)
    {
        PowerLabel.Text = Loc.GetString("warp-drive-window-power-value",
            ("draw", state.PowerDraw),
            ("max", state.PowerDrawMax));

        if (!state.Powered)
        {
            PowerLabel.Text = Loc.GetString("warp-drive-window-power-none");
            PowerLabel.FontColorOverride = Palettes.Status.Critical;
            return;
        }

        // Demand above supply means the grid cannot keep up. Only meaningful while drawing hard.
        var starving = state.PowerDrawMax > 0f && state.PowerDraw + 1f < state.PowerDrawMax;
        PowerLabel.FontColorOverride = starving ? Palettes.Status.Critical : Palettes.Status.Good;
    }

    private void UpdateRange(WarpDriveBuiState state)
    {
        var live = state.Range > 0f;
        RangeLabel.Text = Loc.GetString("warp-drive-window-range-value", ("range", state.Range));
        RangeLabel.FontColorOverride = live ? Palettes.Status.Good : Palettes.Neutral.Base;

        // Dim the row when the drive is contributing nothing, so the one number that matters is
        // the one that is lit.
        RangeLabel.SetOnlyStyleClass(live ? "highlight" : "LabelWeak");
    }

    private void UpdateSpool(WarpDriveBuiState state)
    {
        var spooling = state.DriveState == WarpDriveState.Spooling;
        SpoolBar.Value = state.SpoolProgress;
        SpoolText.Text = spooling
            ? Loc.GetString("warp-drive-window-spool-value", ("pct", (int) (state.SpoolProgress * 100f)))
            : Loc.GetString("warp-drive-window-none");

        // A finished or not-started spool is not a problem, so it stays neutral rather than green.
        SpoolText.FontColorOverride = spooling ? Palettes.Status.Warning : Palettes.Neutral.Base;
    }

    /// <summary>
    ///     Core heat. This is the bar worth watching, because it is the one that ends the round.
    /// </summary>
    private void UpdateHeat(WarpDriveBuiState state)
    {
        HeatBar.Value = state.Heat;
        HeatText.Text = Loc.GetString("warp-drive-window-heat-value", ("pct", (int) (state.Heat * 100f)));

        // Cold is neutral, warm is amber, about to let go is red - via the shared status ramp so
        // it matches every other machine readout in the game.
        HeatText.FontColorOverride = state.Heat switch
        {
            < 0.4f => Palettes.Neutral.Base,
            < 0.75f => Palettes.Status.Warning,
            _ => Palettes.Status.Critical
        };
    }

    private void UpdateTimers(WarpDriveBuiState state)
    {
        if (state.StabilityRemaining >= 0f)
        {
            StabilityLabel.Text = Loc.GetString("warp-drive-window-stability-value",
                ("time", FormatDuration(state.StabilityRemaining)));
            StabilityLabel.FontColorOverride = state.StabilityRemaining < 10f
                ? Palettes.Status.Critical
                : Palettes.Status.Warning;
        }
        else
        {
            StabilityLabel.Text = Loc.GetString("warp-drive-window-none");
            StabilityLabel.FontColorOverride = Palettes.Neutral.Base;
        }

        if (state.CoolDownRemaining > 0f)
        {
            CoolDownLabel.Text = Loc.GetString("warp-drive-window-cooldown-value",
                ("time", FormatDuration(state.CoolDownRemaining)));
            CoolDownLabel.FontColorOverride = Palettes.Status.Warning;
        }
        else
        {
            CoolDownLabel.Text = Loc.GetString("warp-drive-window-none");
            CoolDownLabel.FontColorOverride = Palettes.Neutral.Base;
        }
    }

    /// <summary>
    ///     The one control. Its label says what pressing it will do, which is not always the same
    ///     as what the drive will allow - a cooling drive offers SPOOL UP and quietly refuses.
    /// </summary>
    private void UpdateButton(WarpDriveBuiState state)
    {
        switch (state.DriveState)
        {
            case WarpDriveState.Idle:
                var cooling = state.CoolDownRemaining > 0f;
                ToggleButton.Text = cooling
                    ? Loc.GetString("warp-drive-window-cooling")
                    : Loc.GetString("warp-drive-window-spool-up");
                ToggleButton.Disabled = cooling || !state.Powered;
                break;

            case WarpDriveState.Spooling:
            case WarpDriveState.Engaged:
                ToggleButton.Text = Loc.GetString("warp-drive-window-shut-down");
                ToggleButton.Disabled = false;
                break;

            default:
                ToggleButton.Text = Loc.GetString("warp-drive-window-in-transit");
                ToggleButton.Disabled = true;
                break;
        }
    }

    /// <summary>
    ///     Seconds as m:ss, dropping the sub-second precision.
    /// </summary>
    /// <remarks>
    ///     The obvious <c>TimeSpan</c>.ToString() was tried first and it renders a 2 minute 16
    ///     second cooldown as "0:02:16.6667175", which is both unreadable and visibly noisy as it
    ///     ticks. A countdown nobody can parse is a countdown nobody is watching.
    /// </remarks>
    private static string FormatDuration(float seconds)
    {
        var total = (int) Math.Max(0f, seconds);
        return $"{total / 60:00}:{total % 60:00}";
    }
}