# SPDX-FileCopyrightText: 2024 Velcroboy <107660393+IamVelcroboy@users.noreply.github.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: RoleSilvia
  name: role-name-silvia
  description: role-description-silvia
  setPreference: false
  canBeAntag: false
  playTimeTracker: RoleSilvia
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 4h

- type: startingGear
  id: MobSilviaGear
  equipment:
    eyes: ClothingEyesHudMedical
