// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Pirate.Contractors.Prototypes;
using Content.Shared._Pirate.Knowledge;
using Content.Shared.GameTicking;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Pirate.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class KnowledgeProfileEditor : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _systems = default!;
    [Dependency] private readonly IEntityManager _entities = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public event Action<KnowledgeProfile>? OnApply;

    private SharedKnowledgeSystem _knowledge = default!;
    private KnowledgeClientSystem _clientKnowledge = default!;
    private SpriteSystem _sprites = default!;
    private KnowledgeProfilePrototype? _speciesProfile;
    private KnowledgeProfile _profile = new();
    private string _employerId = string.Empty;
    private string _jobId = SharedGameTicker.FallbackOverflowJob;
    private bool _modified;

    private static readonly Color ProfileColor = Color.FromHex("#6EA8FE");
    private static readonly Color JobColor = Color.FromHex("#55D6BE");
    private static readonly Color EmployerColor = Color.FromHex("#F2C14E");
    private static readonly Color PenaltyColor = Color.FromHex("#E36D6D");
    private static readonly Color PotentialColor = Color.FromHex("#5B606B");

    public KnowledgeProfileEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _knowledge = _systems.GetEntitySystem<SharedKnowledgeSystem>();
        _clientKnowledge = _systems.GetEntitySystem<KnowledgeClientSystem>();
        _sprites = _systems.GetEntitySystem<SpriteSystem>();
        _clientKnowledge.JobChipsChanged += OnJobChipsChanged;

        SaveButton.OnPressed += _ => Apply();
        ResetButton.OnPressed += _ => ResetSelection();
        BuildLegend();
        SetButtons();
    }

    public void SetProfile(HumanoidCharacterProfile profile)
    {
        var highPriorityJob = profile.JobPriorities
            .FirstOrDefault(priority => priority.Value == JobPriority.High)
            .Key;
        _jobId = highPriorityJob.Id ?? SharedGameTicker.FallbackOverflowJob;
        _employerId = profile.Employer;
        SetProfile(profile.Species, profile.Knowledge, preserveContext: true);
    }

    public void SetProfile(ProtoId<SpeciesPrototype> speciesId, KnowledgeProfile profile)
    {
        SetProfile(speciesId, profile, preserveContext: false);
    }

    private void SetProfile(
        ProtoId<SpeciesPrototype> speciesId,
        KnowledgeProfile profile,
        bool preserveContext)
    {
        if (!preserveContext)
        {
            _jobId = SharedGameTicker.FallbackOverflowJob;
            _employerId = string.Empty;
        }

        if (!_prototypes.TryIndex(speciesId, out SpeciesPrototype? species) ||
            !_prototypes.TryIndex(species.Knowledge, out _speciesProfile))
        {
            _speciesProfile = null;
            _profile = new KnowledgeProfile();
            _modified = false;
            Skills.RemoveAllChildren();
            PointsLabel.Text = Loc.GetString("knowledge-editor-profile-unavailable");
            SetButtons();
            return;
        }

        _profile = new KnowledgeProfile(profile);
        _modified = false;
        Rebuild();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _clientKnowledge.JobChipsChanged -= OnJobChipsChanged;

        base.Dispose(disposing);
    }

    private void OnJobChipsChanged()
    {
        if (_speciesProfile is not null)
            Rebuild();
    }

    private void Rebuild()
    {
        Skills.RemoveAllChildren();
        if (_speciesProfile is null)
            return;

        var entries = _knowledge.AllKnowledges
            .Where(pair => pair.Value.Costs is not null)
            .OrderBy(pair => Loc.GetString(_prototypes.Index(pair.Value.Category).Name))
            .ThenBy(pair => _prototypes.Index<EntityPrototype>(pair.Key).Name)
            .ToList();

        ProtoId<KnowledgeCategoryPrototype>? currentCategory = null;
        BoxContainer? categorySkills = null;
        foreach (var (id, component) in entries)
        {
            if (currentCategory != component.Category)
            {
                currentCategory = component.Category;
                var category = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    SeparationOverride = 5,
                };
                var header = new PanelContainer
                {
                    StyleClasses = { KnowledgeStyleClasses.CategoryHeader },
                    HorizontalExpand = true,
                };
                header.AddChild(new Label
                {
                    Text = Loc.GetString(_prototypes.Index(component.Category).Name),
                    StyleClasses = { KnowledgeStyleClasses.CategoryName },
                });
                category.AddChild(header);

                categorySkills = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    SeparationOverride = 4,
                };
                category.AddChild(categorySkills);
                Skills.AddChild(category);
            }

            AddSkillRow(categorySkills!, id, component);
        }

        UpdatePoints();
        SetButtons();
    }

    private void BuildLegend()
    {
        AddLegendItem(ProfileColor, "knowledge-editor-source-profile");
        AddLegendItem(JobColor, "knowledge-editor-source-job");
        AddLegendItem(EmployerColor, "knowledge-editor-source-employer");
        AddLegendItem(PenaltyColor, "knowledge-editor-source-penalty");
        AddLegendItem(PotentialColor, "knowledge-editor-source-potential");
    }

    private void AddLegendItem(Color color, string text)
    {
        Legend.AddChild(new Label
        {
            Text = $"■ {Loc.GetString(text)}",
            FontColorOverride = color,
            StyleClasses = { KnowledgeStyleClasses.SkillDetails },
        });
    }

    private void AddSkillRow(BoxContainer categorySkills, EntProtoId id, KnowledgeComponent component)
    {
        var costs = component.Costs!;
        var prototype = _prototypes.Index<EntityPrototype>(id);
        var racialBase = _speciesProfile!.Profile.Mastery?.GetValueOrDefault(id) ?? 0;
        var selected = _profile.Mastery?.GetValueOrDefault(id) ?? 0;
        var profileMastery = racialBase + selected;

        var row = new PanelContainer
        {
            Name = $"SkillRow{id}",
            StyleClasses = { KnowledgeStyleClasses.SkillRow },
            HorizontalExpand = true,
            ToolTip = prototype.Description,
            MouseFilter = MouseFilterMode.Pass,
        };

        var body = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 6,
            MouseFilter = MouseFilterMode.Pass,
        };
        var summary = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
            MouseFilter = MouseFilterMode.Pass,
        };
        if (component.Sprite is { } sprite)
        {
            summary.AddChild(new TextureRect
            {
                Texture = _sprites.Frame0(sprite),
                MinSize = new System.Numerics.Vector2(30, 30),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                VerticalAlignment = VAlignment.Center,
                MouseFilter = MouseFilterMode.Pass,
            });
        }

        var labels = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            MouseFilter = MouseFilterMode.Pass,
        };
        var name = new Label
        {
            Text = prototype.Name,
            StyleClasses = { KnowledgeStyleClasses.SkillName },
            MouseFilter = MouseFilterMode.Pass,
        };
        var masteryLabel = new Label
        {
            Name = $"SkillLevel{id}",
            StyleClasses = { KnowledgeStyleClasses.SkillDetails },
            MouseFilter = MouseFilterMode.Pass,
        };
        labels.AddChild(name);
        labels.AddChild(masteryLabel);
        summary.AddChild(labels);

        var costLabel = new Label
        {
            StyleClasses = { KnowledgeStyleClasses.SkillExperience },
            VerticalAlignment = VAlignment.Center,
            MouseFilter = MouseFilterMode.Pass,
        };
        summary.AddChild(costLabel);

        var decrease = new Button
        {
            Name = $"Decrease{id}",
            Text = "-",
            MinWidth = 34,
            ToolTip = Loc.GetString("knowledge-editor-decrease"),
        };
        var increase = new Button
        {
            Name = $"Increase{id}",
            Text = "+",
            MinWidth = 34,
            ToolTip = Loc.GetString("knowledge-editor-increase"),
        };
        summary.AddChild(decrease);
        summary.AddChild(increase);

        var bar = CreateSkillBar(id);
        body.AddChild(summary);
        body.AddChild(bar.Frame);
        row.AddChild(body);

        void RefreshRow()
        {
            selected = _profile.Mastery?.GetValueOrDefault(id) ?? 0;
            profileMastery = racialBase + selected;
            var cost = selected >= 0 && selected < costs.Length ? costs[selected] : 0;
            var jobLevel = GetJobLevel(id);
            var employerMastery = GetEmployerMastery(id);
            var finalLevel = SharedKnowledgeSystem.GetProfilePreviewLevel(
                profileMastery,
                jobLevel,
                employerMastery,
                out var profileLevel,
                out var employerLevel);
            masteryLabel.Text = Loc.GetString(
                "knowledge-editor-level-mastery",
                ("mastery", SharedKnowledgeSystem.GetMasteryString(
                    SharedKnowledgeSystem.GetMastery(finalLevel))),
                ("level", finalLevel));
            masteryLabel.FontColorOverride = KnowledgeStyleColors.ForLevel(finalLevel);
            costLabel.Text = Loc.GetString("knowledge-editor-cost", ("cost", cost));

            var breakdown = Loc.GetString(
                "knowledge-editor-breakdown",
                ("profile", profileLevel),
                ("job", Signed(jobLevel)),
                ("employer", Signed(employerLevel)),
                ("total", finalLevel));
            var tooltip = string.IsNullOrWhiteSpace(prototype.Description)
                ? breakdown
                : $"{prototype.Description}\n\n{breakdown}";
            row.ToolTip = tooltip;
            body.ToolTip = tooltip;
            summary.ToolTip = tooltip;
            labels.ToolTip = tooltip;
            name.ToolTip = tooltip;
            masteryLabel.ToolTip = tooltip;
            costLabel.ToolTip = tooltip;
            bar.Frame.ToolTip = tooltip;
            bar.Segments.ToolTip = tooltip;

            RebuildSkillBar(bar.Segments, profileLevel, jobLevel, employerLevel, finalLevel);
            decrease.Disabled = selected <= 0;
            increase.Disabled = profileMastery >= costs.Length - 1 || selected >= costs.Length - 1;
            var color = finalLevel <= 0 ? Color.Gray : Color.White;
            name.Modulate = color;
        }

        void Change(int difference)
        {
            var nextSelected = selected + difference;
            var nextMastery = racialBase + nextSelected;
            if (nextSelected < 0 || nextSelected >= costs.Length || nextMastery >= costs.Length)
                return;

            _profile.Mastery ??= new Dictionary<EntProtoId, int>();
            if (nextSelected == 0)
                _profile.Mastery.Remove(id);
            else
                _profile.Mastery[id] = nextSelected;

            _modified = true;
            RefreshRow();
            UpdatePoints();
            SetButtons();
        }

        decrease.OnPressed += _ => Change(-1);
        increase.OnPressed += _ => Change(1);
        RefreshRow();

        categorySkills.AddChild(row);
    }

    private static (PanelContainer Frame, BoxContainer Segments) CreateSkillBar(EntProtoId id)
    {
        var background = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#15171C"),
            BorderColor = Color.FromHex("#3A3E48"),
            BorderThickness = new Thickness(1),
        };
        background.SetContentMarginOverride(StyleBox.Margin.All, 1);

        var segments = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            MinHeight = 10,
            SeparationOverride = 1,
            MouseFilter = MouseFilterMode.Pass,
        };
        var frame = new PanelContainer
        {
            Name = $"SkillBar{id}",
            HorizontalExpand = true,
            PanelOverride = background,
            MouseFilter = MouseFilterMode.Pass,
        };
        frame.AddChild(segments);
        return (frame, segments);
    }

    private static void RebuildSkillBar(
        BoxContainer segments,
        int profileLevel,
        int jobLevel,
        int employerLevel,
        int finalLevel)
    {
        segments.RemoveAllChildren();

        var profileBeforeJob = Math.Clamp(profileLevel, 0, 100);
        var afterJob = Math.Clamp(profileLevel + jobLevel, 0, 100);
        var visibleProfile = Math.Min(profileBeforeJob, afterJob);
        var visibleJob = Math.Max(afterJob - visibleProfile, 0);
        var visibleEmployer = Math.Min(
            Math.Max(employerLevel, 0),
            Math.Max(finalLevel - afterJob, 0));
        var visiblePenalty = jobLevel < 0
            ? Math.Min(-jobLevel, 100 - finalLevel)
            : 0;
        var visiblePotential = Math.Max(
            100 - visibleProfile - visibleJob - visibleEmployer - visiblePenalty,
            0);

        AddSegment(segments, visibleProfile, ProfileColor);
        AddSegment(segments, visibleJob, JobColor);
        AddSegment(segments, visibleEmployer, EmployerColor);
        AddSegment(segments, visiblePenalty, PenaltyColor);
        AddSegment(segments, visiblePotential, PotentialColor);
    }

    private static void AddSegment(BoxContainer segments, int amount, Color color)
    {
        if (amount <= 0)
            return;

        segments.AddChild(new PanelContainer
        {
            HorizontalExpand = true,
            SizeFlagsStretchRatio = amount,
            PanelOverride = new StyleBoxFlat { BackgroundColor = color },
            MouseFilter = MouseFilterMode.Pass,
        });
    }

    private int GetJobLevel(EntProtoId id)
    {
        if (!_clientKnowledge.JobChips.TryGetValue(_jobId, out var chips))
            return 0;

        var total = 0;
        foreach (var chipId in chips)
        {
            if (!_prototypes.TryIndex<EntityPrototype>(chipId, out var chip) ||
                !chip.TryGetComponent<KnowledgeGrantOnWearComponent>(out var grant, _entities.ComponentFactory))
                continue;

            total += grant.Skills.GetValueOrDefault(id);
        }

        return total;
    }

    private int GetEmployerMastery(EntProtoId id)
    {
        return _prototypes.TryIndex<EmployerPrototype>(_employerId, out var employer)
            ? employer.KnowledgeBonuses.GetValueOrDefault(id)
            : 0;
    }

    private static string Signed(int value)
        => value > 0 ? $"+{value}" : value.ToString();

    private void UpdatePoints()
    {
        if (_speciesProfile is null)
            return;

        var remaining = _speciesProfile.PointsLimit - _knowledge.ProfileCost(_profile);
        PointsLabel.Text = Loc.GetString("knowledge-editor-points", ("points", remaining));
        PointsLabel.FontColorOverride = remaining < 0 ? Color.Red : Color.White;
    }

    private void SetButtons()
    {
        var valid = _speciesProfile is not null &&
                    _speciesProfile.PointsLimit - _knowledge.ProfileCost(_profile) >= 0;
        SaveButton.Disabled = !_modified || !valid;
        ResetButton.Disabled = _speciesProfile is null ||
                               (!_modified && (_profile.Mastery is null || _profile.Mastery.Count == 0));
    }

    private void Apply()
    {
        if (SaveButton.Disabled)
            return;

        OnApply?.Invoke(new KnowledgeProfile(_profile));
        _modified = false;
        SetButtons();
    }

    private void ResetSelection()
    {
        _profile = new KnowledgeProfile();
        _modified = true;
        Rebuild();
    }
}
