// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Pirate.Knowledge;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Pirate.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class KnowledgeTab : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _systems = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    private SharedKnowledgeSystem _knowledge = default!;
    private SpriteSystem _sprites = default!;

    public KnowledgeTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _knowledge = _systems.GetEntitySystem<SharedKnowledgeSystem>();
        _sprites = _systems.GetEntitySystem<SpriteSystem>();
    }

    public void UpdateKnowledgeTab(EntityUid player)
    {
        KnowledgeBox.RemoveAllChildren();

        var skills = _knowledge.GetAllKnowledge(player)?
            .Where(skill => !skill.Comp.Hidden)
            .Select(skill => (Skill: skill, Info: _knowledge.GetKnowledgeInfo(skill)))
            .OrderBy(data => Loc.GetString(_prototypes.Index(data.Skill.Comp.Category).Name), StringComparer.CurrentCulture)
            .ThenBy(data => data.Info.Name, StringComparer.CurrentCulture)
            .ToList();

        KnowledgePlaceholder.Visible = skills is null || skills.Count == 0;
        if (skills is null)
            return;

        ProtoId<KnowledgeCategoryPrototype>? currentCategory = null;
        foreach (var (skill, info) in skills)
        {
            if (currentCategory != skill.Comp.Category)
            {
                currentCategory = skill.Comp.Category;
                KnowledgeBox.AddChild(new Label
                {
                    Text = Loc.GetString(_prototypes.Index(skill.Comp.Category).Name),
                    StyleClasses = { "LabelHeading" },
                    Margin = new Thickness(0, 6, 0, 2),
                });
            }

            KnowledgeBox.AddChild(CreateSkillRow(info));
        }
    }

    private Control CreateSkillRow(KnowledgeInfo info)
    {
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            MinHeight = 42,
            ToolTip = info.Description,
            MouseFilter = MouseFilterMode.Pass,
        };

        var icon = new TextureRect
        {
            MinSize = new System.Numerics.Vector2(32, 32),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            Margin = new Thickness(0, 0, 8, 0),
        };
        if (info.Sprite is { } sprite)
            icon.Texture = _sprites.Frame0(sprite);

        var labels = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        labels.AddChild(new Label { Text = info.Name, Modulate = info.Color });
        labels.AddChild(new Label
        {
            Text = info.Level,
            Modulate = info.Color,
            StyleClasses = { "LabelSubText" },
        });

        var progress = new ProgressBar
        {
            MinValue = 0,
            MaxValue = Math.Max(info.ExperienceCost, 1),
            Value = Math.Min(info.Experience, Math.Max(info.ExperienceCost, 1)),
            MinWidth = 110,
            VerticalAlignment = VAlignment.Center,
        };

        row.AddChild(icon);
        row.AddChild(labels);
        row.AddChild(progress);
        return row;
    }
}
