- type: job
  id: InterdyneEngineer
  name: job-name-interdyne-engineer
  description: job-description-interdyne-engineer
  icon: "JobIconInterdyneEngineer"
  canBeAntag: false
  playTimeTracker: JobInterdyneEngineer
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipEducation
    - SkillChipDatabase
    - SkillChipTool
  access:
    - Maintenance
    - External
    - Interdyne
    - InterdyneCommand