- type: job
  id: InterdyneService
  name: job-name-interdyne-service
  description: job-description-interdyne-service
  icon: "JobIconInterdyneService"
  canBeAntag: false
  playTimeTracker: JobInterdyneService
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipEducation
    - SkillChipShortBlade
  access:
    - Maintenance
    - External
    - Interdyne
    - InterdyneCommand