- type: job
  id: InterdynePilot
  name: job-name-interdyne-pilot
  description: job-description-interdyne-pilot
  icon: "JobIconInterdynePilot"
  canBeAntag: false
  playTimeTracker: JobInterdynePilot
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipEducation
    - SkillChipPistol
  access:
    - Maintenance
    - External
    - Interdyne
    - InterdyneCommand