- type: job
  id: Interdyne
  name: job-name-interdyne
  description: job-description-interdyne
  icon: "JobIconInterdyne"
  canBeAntag: false
  playTimeTracker: JobInterdyne
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipEducation
    - SkillChipDatabase
  access:
    - Maintenance
    - External
    - Interdyne
    - InterdyneCommand