// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Pirate.ListeningPost.DropConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Timing;

namespace Content.Client._Pirate.ListeningPost.DropConsole;

[GenerateTypedNameReferences]
public sealed partial class SyndicateDropConsoleWindow : FancyWindow
{
    private static readonly Color TargetColor = Color.LimeGreen;

    private static readonly Color HistoryColor = Color.Red;

    private static readonly Color HistorySelectedColor = Color.Orange;

    private static readonly Color WarningColor = Color.FromHex("#ff5555");

    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private readonly SharedTransformSystem _transform;

    public event Action<bool>? OnSetMode;
    public event Action<NetEntity, Vector2>? OnSelectTile;
    public event Action<NetEntity, Vector2i>? OnNudgeTarget;
    public event Action? OnClearTarget;
    public event Action? OnLaunch;
    public event Action? OnPodSend;

    private SyndicateDropConsoleUiState? _state;
    private EntityUid? _rootGrid;

    private int? _selectedRecord;

    public SyndicateDropConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _transform = _entMan.System<SharedTransformSystem>();

        NavMapScreen.ZLevelSelectorEnabled = true;
        NavMapScreen.ZFilterTrackedBlipsToDisplayedMap = true;
        NavMapScreen.TileSelectedAction += OnMapClicked;
        NavMapScreen.ZLevelSelectedAction += (_, _) => UpdateTarget();

        ModeButton.OnPressed += _ => OnSetMode?.Invoke(!(_state?.Manual ?? false));
        ClearTargetButton.OnPressed += _ => OnClearTarget?.Invoke();
        LaunchButton.OnPressed += _ => OnLaunch?.Invoke();
        PodSendButton.OnPressed += _ => OnPodSend?.Invoke();

        TargetUp.OnPressed += _ => Nudge(new Vector2i(0, 1));
        TargetDown.OnPressed += _ => Nudge(new Vector2i(0, -1));
        TargetLeft.OnPressed += _ => Nudge(new Vector2i(-1, 0));
        TargetRight.OnPressed += _ => Nudge(new Vector2i(1, 0));
    }

    public void Update(SyndicateDropConsoleUiState state)
    {
        _state = state;

        var grid = _entMan.GetEntity(state.TargetGrid);

        if (grid != _rootGrid)
        {
            _rootGrid = grid;
            NavMapScreen.MapUid = grid;
            NavMapScreen.SetZLevelSelectorRoot(grid);
            NavMapScreen.ForceNavMapUpdate();

            StationName.Text = _entMan.TryGetComponent<MetaDataComponent>(grid, out var meta)
                ? meta.EntityName
                : Loc.GetString("syndicate-drop-console-no-station");
        }

        ModeButton.Text = Loc.GetString(state.Manual
            ? "syndicate-drop-console-mode-manual"
            : "syndicate-drop-console-mode-auto");
        ModeDescription.SetMessage(Loc.GetString(state.Manual
            ? "syndicate-drop-console-mode-manual-desc"
            : "syndicate-drop-console-mode-auto-desc"));

        UpdateTarget();
        UpdateCharges(state);
        UpdatePod(state);
        UpdateHistory(state);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_state == null)
        {
            Countdown.Text = Loc.GetString("syndicate-drop-console-countdown-unknown");
            return;
        }

        var remaining = _state.NextDrop - _timing.CurTime;

        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        Countdown.Text = $"{(int) remaining.TotalMinutes:D2}:{remaining.Seconds:D2}";

        UpdatePod(_state);
    }

    private void Nudge(Vector2i delta)
    {
        if (NavMapScreen.MapUid is not { } displayed)
            return;

        OnNudgeTarget?.Invoke(_entMan.GetNetEntity(displayed), delta);
    }

    private void OnMapClicked(EntityUid grid, Vector2 localPosition)
    {
        OnSelectTile?.Invoke(_entMan.GetNetEntity(grid), localPosition);
    }

    private void UpdateTarget()
    {
        NavMapScreen.TrackedCoordinates.Clear();

        if (_state != null)
        {
            for (var i = 0; i < _state.DropHistory.Count; i++)
            {
                var record = _state.DropHistory[i];

                if (TryGetTileCentre(_entMan.GetEntity(record.Grid), record.Tile) is not { } past)
                    continue;

                NavMapScreen.TrackedCoordinates[past] =
                    (true, i == _selectedRecord ? HistorySelectedColor : HistoryColor);
            }
        }

        if (_state?.SelectedTile is not { } tile ||
            TryGetTileCentre(_entMan.GetEntity(_state.SelectedGrid), tile) is not { } target)
        {
            TargetPos.Text = Loc.GetString("syndicate-drop-console-target-none");
            return;
        }

        TargetPos.Text = FormatCoordinates(target);
        NavMapScreen.TrackedCoordinates[target] = (true, TargetColor);
    }

    private void UpdatePod(SyndicateDropConsoleUiState state)
    {
        PodSendButton.Disabled = !state.PadLinked;
        PodWarning.SetMessage(Loc.GetString("syndicate-drop-console-pod-warning"), WarningColor);

        if (!state.PadLinked)
        {
            PodStatus.Text = Loc.GetString("syndicate-drop-console-pod-unlinked");
            return;
        }

        var remaining = state.PodCooldownEnd - _timing.CurTime;

        PodStatus.Text = remaining > TimeSpan.Zero
            ? Loc.GetString("syndicate-drop-console-pod-traceable",
                ("time", $"{(int) remaining.TotalMinutes:D2}:{remaining.Seconds:D2}"))
            : Loc.GetString("syndicate-drop-console-pod-ready");
    }

    private void UpdateHistory(SyndicateDropConsoleUiState state)
    {
        HistoryList.RemoveAllChildren();

        HistoryHeader.Text = Loc.GetString("syndicate-drop-console-history-header", ("count", state.DropHistory.Count));

        if (_selectedRecord >= state.DropHistory.Count)
            _selectedRecord = null;

        if (state.DropHistory.Count == 0)
        {
            HistoryList.AddChild(new Label
            {
                Text = Loc.GetString("syndicate-drop-console-history-empty"),
                StyleClasses = { "WindowFooterText" },
                HorizontalAlignment = HAlignment.Center,
            });

            return;
        }

        for (var i = 0; i < state.DropHistory.Count; i++)
        {
            var index = i;
            var record = state.DropHistory[i];

            var coordinates = Loc.GetString("syndicate-drop-console-coordinates",
                ("x", record.MapPosition.X),
                ("y", record.MapPosition.Y));

            var time = $"{(int) record.Time.TotalMinutes:D2}:{record.Time.Seconds:D2}";
            var mode = Loc.GetString(ModeBadge(record.Mode));

            var text = record.Mode == SyndicateDropMode.Pod
                ? Loc.GetString("syndicate-drop-console-history-entry-pod",
                    ("time", time),
                    ("coordinates", coordinates),
                    ("mode", mode))
                : Loc.GetString("syndicate-drop-console-history-entry",
                    ("time", time),
                    ("price", record.Price),
                    ("coordinates", coordinates),
                    ("mode", mode));

            var button = new Button
            {
                Text = text,
                StyleClasses = { "OpenBoth" },
                ClipText = true,
                Margin = new Thickness(0f, 1f),
            };

            var grid = _entMan.GetEntity(record.Grid);
            var tile = record.Tile;
            button.OnPressed += _ =>
            {
                _selectedRecord = index;
                JumpTo(grid, tile);
            };

            HistoryList.AddChild(button);
        }
    }

    private static string ModeBadge(SyndicateDropMode mode)
    {
        return mode switch
        {
            SyndicateDropMode.Manual => "syndicate-drop-console-mode-badge-manual",
            SyndicateDropMode.Pod => "syndicate-drop-console-mode-badge-pod",
            _ => "syndicate-drop-console-mode-badge-automatic",
        };
    }

    private void JumpTo(EntityUid? grid, Vector2i tile)
    {
        if (TryGetTileCentre(grid, tile) is not { } coords)
            return;

        if (NavMapScreen.MapUid != grid)
        {
            NavMapScreen.MapUid = grid;
            NavMapScreen.ForceNavMapUpdate();
        }

        NavMapScreen.CenterToCoordinates(coords);
    }

    private EntityCoordinates? TryGetTileCentre(EntityUid? grid, Vector2i tile)
    {
        if (grid is not { } gridUid || !_entMan.TryGetComponent<MapGridComponent>(gridUid, out var gridComp))
            return null;

        return new EntityCoordinates(gridUid,
            new Vector2((tile.X + 0.5f) * gridComp.TileSize, (tile.Y + 0.5f) * gridComp.TileSize));
    }

    private string FormatCoordinates(EntityCoordinates coordinates)
    {
        var position = _transform.ToMapCoordinates(coordinates).Position;

        return Loc.GetString("syndicate-drop-console-coordinates",
            ("x", (int) position.X),
            ("y", (int) position.Y));
    }

    private void UpdateCharges(SyndicateDropConsoleUiState state)
    {
        ChargeHeader.Text = Loc.GetString("syndicate-drop-console-charges-header",
            ("count", state.Charges),
            ("max", state.MaxCharges));

        LaunchButton.Disabled = state.Charges <= 0;
    }
}
