// SPDX-FileCopyrightText: 2025 Tyranex <bobthezombie4@gmail.com>
//
// SPDX-License-Identifier: MIT

using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client._Pirate.Lobby.UI.Loadouts;
using Content.Shared.StatusIcon;
using Content.Client.UserInterface.Controls;
using Content.Shared._Pirate.MalfAI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Client.GameObjects;

namespace Content.Client._Pirate.MalfAI.VoiceModulator;

[GenerateTypedNameReferences]
public sealed partial class MalfVoiceModulatorWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IEntityManager _entities = default!;
    public event Action<string>? OnConfirm;
    public event Action<string?>? OnVerbChanged;
    public event Action<string?>? OnSoundChanged;
    public event Action<string?>? OnJobIconChanged;
    public event Action? OnToggle;
    public event Action? OnAccentToggle;
    public event Action<NetEntity>? OnCrewSelected;
    public event Action? OnRefreshCrew;

    private readonly List<MalfVoiceModulatorOption> _verbs = new();
    private readonly List<MalfVoiceModulatorOption> _sounds = new();
    private readonly List<MalfVoiceModulatorOption> _jobIcons = new();
    private readonly List<MalfVoiceModulatorCrewMember> _crew = new();
    private readonly List<(MalfVoiceModulatorCrewMember Member, ContainerButton Button)> _crewButtons = new();

    public MalfVoiceModulatorWindow(Font? malfFont)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RootBackdrop.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#202225") };

        Title = Loc.GetString("malf-voice-window-title");
        HeaderLabel.Text = Loc.GetString("malf-voice-header-label");
        NameEdit.PlaceHolder = Loc.GetString("malf-voice-name-placeholder");
        ConfirmButton.Text = Loc.GetString("malf-voice-confirm-button");
        AccentButton.Text = Loc.GetString("voice-mask-name-change-accent-toggle");
        ActiveButton.Text = Loc.GetString("voice-mask-name-change-toggle");

        ConfirmButton.OnPressed += _ => OnConfirm?.Invoke(NameEdit.Text?.Trim() ?? string.Empty);
        VerbSelector.OnItemSelected += args => OnVerbChanged?.Invoke(GetOption(_verbs, args.Id));
        SoundSelector.OnItemSelected += args => OnSoundChanged?.Invoke(GetOption(_sounds, args.Id));
        JobIconSelector.OnItemSelected += args => OnJobIconChanged?.Invoke(GetOption(_jobIcons, args.Id));
        ActiveButton.OnPressed += _ => OnToggle?.Invoke();
        AccentButton.OnPressed += _ => OnAccentToggle?.Invoke();
        CrewSearch.OnTextChanged += _ => FilterCrew();
        RefreshCrewButton.OnPressed += _ => OnRefreshCrew?.Invoke();
    }

    public void UpdateState(MalfVoiceModulatorState state)
    {
        NameEdit.Text = state.Name;
        ActiveButton.Pressed = state.Active;
        AccentButton.Pressed = state.AccentHide;
        Reload(VerbSelector, _verbs, state.Verbs, state.Verb);
        Reload(SoundSelector, _sounds, state.Sounds, state.SpeechSounds);
        Reload(JobIconSelector, _jobIcons, state.JobIcons, state.JobIcon);
        if (!_crew.SequenceEqual(state.Crew))
        {
            _crew.Clear();
            _crew.AddRange(state.Crew);
            PopulateCrew();
        }
        FilterCrew();
    }

    private void PopulateCrew()
    {
        CrewList.DisposeAllChildren();
        _crewButtons.Clear();
        var sprites = _entities.System<SpriteSystem>();
        foreach (var member in _crew)
        {
            var color = member.Health switch
            {
                MalfVoiceCrewHealth.Healthy => Color.FromHex("#509121"),
                MalfVoiceCrewHealth.Wounded => Color.FromHex("#DA7B0C"),
                MalfVoiceCrewHealth.Critical => Color.FromHex("#C61F1F"),
                MalfVoiceCrewHealth.Dead => Color.FromHex("#722626"),
                _ => Color.FromHex("#515158"),
            };
            var button = new ContainerButton
            {
                StyleBoxOverride = LoadoutStyles.RoundedFilled(color, padding: 6f),
                HorizontalExpand = true,
                MinHeight = 48,
                ToolTip = $"{member.Name}\n{member.Job}\n{Loc.GetString($"malf-voice-health-{member.Health.ToString().ToLowerInvariant()}")}",
            };
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
            if (_prototypes.TryIndex<JobIconPrototype>(member.JobIcon, out var icon))
                row.AddChild(new TextureRect
                {
                    Texture = sprites.Frame0(icon.Icon),
                    MinSize = new Vector2(24, 24),
                    MaxSize = new Vector2(24, 24),
                    VerticalAlignment = VAlignment.Center,
                    Stretch = TextureRect.StretchMode.KeepAspectCentered,
                });
            var labels = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true };
            labels.AddChild(new Label { Text = member.Name, ClipText = true, HorizontalExpand = true });
            labels.AddChild(new Label { Text = member.Job, ClipText = true, HorizontalExpand = true });
            row.AddChild(labels);
            button.AddChild(row);
            button.OnPressed += _ => OnCrewSelected?.Invoke(member.Entity);
            CrewList.AddChild(button);
            _crewButtons.Add((member, button));
        }
    }

    private void FilterCrew()
    {
        var search = CrewSearch.Text.Trim();
        var visible = false;
        foreach (var (member, button) in _crewButtons)
        {
            button.Visible = member.Name.Contains(search, StringComparison.CurrentCultureIgnoreCase) ||
                member.Job.Contains(search, StringComparison.CurrentCultureIgnoreCase);
            visible |= button.Visible;
        }
        CrewEmptyLabel.Visible = !visible;
    }

    private static void Reload(OptionButton button, List<MalfVoiceModulatorOption> target,
        List<MalfVoiceModulatorOption> options, string? selected)
    {
        target.Clear();
        target.AddRange(options);
        button.Clear();
        for (var i = 0; i < target.Count; i++)
        {
            button.AddItem(target[i].Name);
            button.SetItemMetadata(i, target[i].Id);
            if (target[i].Id == (selected ?? string.Empty))
                button.SelectId(i);
        }
    }

    private static string? GetOption(List<MalfVoiceModulatorOption> options, int id)
    {
        if (id < 0 || id >= options.Count)
            return null;
        return string.IsNullOrEmpty(options[id].Id) ? null : options[id].Id;
    }
}
