// SPDX-FileCopyrightText: 2025 Tyranex <bobthezombie4@gmail.com>
//
// SPDX-License-Identifier: MIT

using System;
using System.Collections.Generic;
using Content.Client._Pirate.MalfAI.Theme;
using Content.Client.UserInterface.Controls;
using Content.Shared._Pirate.MalfAI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.MalfAI.VoiceModulator;

[GenerateTypedNameReferences]
public sealed partial class MalfVoiceModulatorWindow : FancyWindow
{
    [Dependency] private readonly IResourceCache _resCache = default!;

    public event Action<string>? OnConfirm;
    public event Action<string?>? OnVerbChanged;
    public event Action<string?>? OnSoundChanged;
    public event Action<string?>? OnJobIconChanged;
    public event Action? OnToggle;
    public event Action? OnAccentToggle;

    private readonly List<MalfVoiceModulatorOption> _verbs = new();
    private readonly List<MalfVoiceModulatorOption> _sounds = new();
    private readonly List<MalfVoiceModulatorOption> _jobIcons = new();

    public MalfVoiceModulatorWindow(Font? malfFont)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RootBackdrop.PanelOverride = MalfUiTheme.CreateBackdropStyle();
        RootBackdrop.AddChild(MalfEffectOverlay.CreateStaticOverlay());
        var buttonStyle = MalfUiTheme.CreateButtonStyle(MalfUiTheme.Accent);

        Title = Loc.GetString("malf-voice-window-title");
        HeaderLabel.Text = Loc.GetString("malf-voice-header-label");
        NameEdit.PlaceHolder = Loc.GetString("malf-voice-name-placeholder");
        ConfirmButton.Text = Loc.GetString("malf-voice-confirm-button");
        AccentButton.Text = Loc.GetString("voice-mask-name-change-accent-toggle");
        ActiveButton.Text = Loc.GetString("voice-mask-name-change-toggle");
        RootBackdrop.Stylesheet = MalfUiTheme.GetCachedStylesheet(_resCache, 12);
        ConfirmButton.StyleBoxOverride = buttonStyle;
        NameEdit.StyleBoxOverride = MalfUiTheme.CreateButtonStyle(MalfUiTheme.Accent);

        ConfirmButton.OnPressed += _ => OnConfirm?.Invoke(NameEdit.Text?.Trim() ?? string.Empty);
        VerbSelector.OnItemSelected += args => OnVerbChanged?.Invoke(GetOption(_verbs, args.Id));
        SoundSelector.OnItemSelected += args => OnSoundChanged?.Invoke(GetOption(_sounds, args.Id));
        JobIconSelector.OnItemSelected += args => OnJobIconChanged?.Invoke(GetOption(_jobIcons, args.Id));
        ActiveButton.OnPressed += _ => OnToggle?.Invoke();
        AccentButton.OnPressed += _ => OnAccentToggle?.Invoke();
    }

    public void UpdateState(MalfVoiceModulatorState state)
    {
        NameEdit.Text = state.Name;
        ActiveButton.Pressed = state.Active;
        AccentButton.Pressed = state.AccentHide;
        Reload(VerbSelector, _verbs, state.Verbs, state.Verb);
        Reload(SoundSelector, _sounds, state.Sounds, state.SpeechSounds);
        Reload(JobIconSelector, _jobIcons, state.JobIcons, state.JobIcon);
    }

    private static void Reload(OptionButton button, List<MalfVoiceModulatorOption> target,
        List<MalfVoiceModulatorOption> options, string? selected)
    {
        target.Clear();
        target.AddRange(options);
        button.Clear();
        for (var i = 0; i < target.Count; i++)
        {
            button.AddItem(target[i].Name);
            button.SetItemMetadata(i, target[i].Id);
            if (target[i].Id == (selected ?? string.Empty))
                button.SelectId(i);
        }
    }

    private static string? GetOption(List<MalfVoiceModulatorOption> options, int id)
    {
        if (id < 0 || id >= options.Count)
            return null;
        return string.IsNullOrEmpty(options[id].Id) ? null : options[id].Id;
    }
}
