using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client._Pirate.Lobby.UI.Loadouts;
using Content.Client._Pirate.UserInterface.Controls;
using Content.Shared._Pirate.Ghost;
using Content.Shared.Ghost;
using Content.Shared.Mobs;
using Content.Shared.Radio;
using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using PirateWrapContainer = Content.Client._Pirate.UserInterface.Controls.WrapContainer;

namespace Content.Client._Pirate.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindowGoob : DefaultWindow
    {
        private List<(string RawName, NetEntity Entity, GhostWarpType Type, int ObserverCount, string JobIconId, MobState MobState, string ProfessionTitle, GhostWarpHealthState HealthState, string DepartmentId, string GroupId)> _warps = new();
        private readonly Dictionary<NetEntity, ChipState> _entityToChip = new();

        private sealed record ChipState(ContainerButton Chip, StyleBoxTexture StyleBox, Label NameLabel, BoxContainer ObserverBlock, Label ObserverCountLabel, string ProfessionTitle, GhostWarpHealthState HealthState, string DepartmentId, string JobIconId, string GroupId);
        private string _searchText = string.Empty;
        private readonly Dictionary<GhostWarpType, bool> _sectionExpandedState = new();

        private enum ViewMode { Health, Department }
        private ViewMode _viewMode = ViewMode.Health;

        private bool _separateGroups = true;

        private IPrototypeManager? _prototypeManager;
        private SpriteSystem? _spriteSystem;

        private IPrototypeManager PrototypeManager => _prototypeManager ??= IoCManager.Resolve<IPrototypeManager>();
        private SpriteSystem SpriteSystem => _spriteSystem ??= IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

        private static readonly string[] SectionTitleKeys = new[]
        {
            "ghost-target-window-filter-places",
            "ghost-target-window-filter-players",
            "ghost-target-window-filter-dead",
            "ghost-target-window-filter-ghosts",
            "ghost-target-window-filter-mobs"
        };
        private static readonly GhostWarpType[] SectionOrder = new[] { GhostWarpType.Player, GhostWarpType.Dead, GhostWarpType.Ghost, GhostWarpType.Mob, GhostWarpType.Location };

        public event Action<NetEntity>? WarpClicked;
        public event Action? OnGhostnadoClicked;
        public event Action? RefreshPressed;

        private const string RefreshIconPath = "/Textures/Interface/VerbIcons/refresh.svg.192dpi.png";
        private const string ObserverIconPath = "/Textures/_Pirate/Interface/VerbIcons/ghost.svg.192dpi.png";
        private const float IconSize = 20f;
        private const string JobIconBorgId = "JobIconBorg";
        private static readonly Color GroupHeaderTextColor = new(0.78f, 0.78f, 0.80f);
        private const int GroupTitleGapAbove = 2;
        private const int GroupTitleGapBelow = 2;
        private static readonly Color SiliconColorFallback = new(0x5e / 255f, 0xd7 / 255f, 0xaa / 255f);

        public GhostTargetWindowGoob()
        {
            RobustXamlLoader.Load(this);

            var roundedTeleportStyle = LoadoutStyles.RoundedBordered(Color.White, padding: 1f, patchMargin: 5f);
            roundedTeleportStyle.SetContentMarginOverride(StyleBox.Margin.Top, 3);
            roundedTeleportStyle.SetContentMarginOverride(StyleBox.Margin.Bottom, 5);
            GhostnadoButton.StyleBoxOverride = roundedTeleportStyle;

            var roundedRefreshStyle = LoadoutStyles.RoundedBordered(Color.White, padding: 1f, patchMargin: 5f);
            roundedRefreshStyle.SetContentMarginOverride(StyleBox.Margin.Top, 4);
            roundedRefreshStyle.SetContentMarginOverride(StyleBox.Margin.Bottom, 4);
            RefreshButton.StyleBoxOverride = roundedRefreshStyle;
            GhostnadoButton.MaxSize = new Vector2(float.PositiveInfinity, 30f);
            RefreshButton.MaxSize = new Vector2(float.PositiveInfinity, 30f);
            GhostnadoButton.Label.VerticalAlignment = VAlignment.Stretch;
            GhostnadoButton.Label.VAlign = Label.VAlignMode.Center;

            var roundedToggleStyle = LoadoutStyles.RoundedBordered(Color.White, padding: 1f, patchMargin: 5f);
            roundedToggleStyle.SetContentMarginOverride(StyleBox.Margin.Top, 0);
            roundedToggleStyle.SetContentMarginOverride(StyleBox.Margin.Bottom, 0);
            roundedToggleStyle.SetPadding(StyleBox.Margin.Top, 0);
            roundedToggleStyle.SetPadding(StyleBox.Margin.Bottom, 2);
            ViewModeButton.StyleBoxOverride = roundedToggleStyle;
            ViewModeButton.MaxSize = new Vector2(float.PositiveInfinity, 24f);
            ViewModeButton.Label.VerticalAlignment = VAlignment.Stretch;
            ViewModeButton.Label.VAlign = Label.VAlignMode.Center;

            var roundedGroupToggleStyle = LoadoutStyles.RoundedBordered(Color.White, padding: 1f, patchMargin: 5f);
            roundedGroupToggleStyle.SetContentMarginOverride(StyleBox.Margin.Top, 0);
            roundedGroupToggleStyle.SetContentMarginOverride(StyleBox.Margin.Bottom, 0);
            roundedGroupToggleStyle.SetPadding(StyleBox.Margin.Top, 0);
            roundedGroupToggleStyle.SetPadding(StyleBox.Margin.Bottom, 2);
            GroupModeButton.StyleBoxOverride = roundedGroupToggleStyle;
            GroupModeButton.MaxSize = new Vector2(float.PositiveInfinity, 24f);
            GroupModeButton.Label.VerticalAlignment = VAlignment.Stretch;
            GroupModeButton.Label.VAlign = Label.VAlignMode.Center;

            SearchBar.OnTextChanged += OnSearchTextChanged;
            GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
            RefreshButton.OnPressed += _ => RefreshPressed?.Invoke();

            RefreshButton.RemoveAllChildren();
            var refreshIcon = new TextureRect
            {
                TexturePath = RefreshIconPath,
                MinSize = new Vector2(IconSize, IconSize),
                MaxSize = new Vector2(IconSize, IconSize),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };
            RefreshButton.AddChild(refreshIcon);
            RefreshButton.TooltipSupplier = _ => new Tooltip { Text = Loc.GetString("ghost-target-window-refresh-tooltip") };

            ViewModeButton.OnPressed += CycleViewMode;
            UpdateViewModeButtonText();

            GroupModeButton.OnPressed += ToggleGroupMode;
            UpdateGroupModeButtonText();
        }

        public void UpdateWarps(IEnumerable<GhostWarp> warps)
        {
            _warps = warps
                .OrderBy(w => w.Type)
                .ThenBy(w => w.DisplayName, Comparer<string>.Create(
                    (x, y) => string.Compare(x, y, StringComparison.Ordinal)))
                .Select(w => (w.DisplayName, w.Entity, w.Type, w.ObserverCount, w.JobIconId, w.MobState, w.ProfessionTitle, w.HealthState, w.DepartmentId, w.GroupId))
                .ToList();
        }

        private static Color GetColorForHealthState(GhostWarpHealthState healthState)
        {
            return healthState switch
            {
                GhostWarpHealthState.Healthy => new Color(0x50 / 255f, 0x91 / 255f, 0x21 / 255f),
                GhostWarpHealthState.Wounded => new Color(0xda / 255f, 0x7b / 255f, 0x0c / 255f),
                GhostWarpHealthState.Critical => new Color(0xc6 / 255f, 0x1f / 255f, 0x1f / 255f),
                _ => new Color(0x73 / 255f, 0x73 / 255f, 0x73 / 255f)
            };
        }

        private Color GetColorForDepartment(string? departmentId)
        {
            if (!string.IsNullOrWhiteSpace(departmentId) &&
                PrototypeManager.TryIndex<DepartmentPrototype>(departmentId, out var dept))
                return DimForDisplay(dept.Color);
            return new Color(0x73 / 255f, 0x73 / 255f, 0x73 / 255f);
        }

        private Color GetColorForSilicon()
        {
            if (PrototypeManager.TryIndex<RadioChannelPrototype>("Binary", out var binary))
                return DimForDisplay(binary.Color);
            return DimForDisplay(SiliconColorFallback);
        }

        private Color? GetColorForGroup(string? groupId)
        {
            if (string.IsNullOrEmpty(groupId) || !PrototypeManager.TryIndex<GhostWarpGroupPrototype>(groupId, out var group))
                return null;
            if (group.Color is { } color)
                return color;
            if (group.RadioChannel is { } channel && PrototypeManager.TryIndex(channel, out var radio))
                return radio.Color;
            return null;
        }

        private Color GetDisplayColor(ViewMode mode, GhostWarpHealthState healthState, string professionTitle, string departmentId, string? jobIconId, string? groupId)
        {
            if (mode == ViewMode.Department && GetColorForGroup(groupId) is { } groupColor)
                return groupColor;
            if (mode == ViewMode.Department && jobIconId == JobIconBorgId)
                return GetColorForSilicon();
            return mode == ViewMode.Department
                ? GetColorForDepartment(departmentId)
                : GetColorForHealthState(healthState);
        }

        private void CycleViewMode(BaseButton.ButtonEventArgs _)
        {
            _viewMode = _viewMode == ViewMode.Health ? ViewMode.Department : ViewMode.Health;
            UpdateViewModeButtonText();
            foreach (var state in _entityToChip.Values)
            {
                var color = GetDisplayColor(_viewMode, state.HealthState, state.ProfessionTitle, state.DepartmentId, state.JobIconId, state.GroupId);
                state.StyleBox.Modulate = color;
            }
        }

        private void UpdateViewModeButtonText()
        {
            var key = _viewMode == ViewMode.Health ? "ghost-target-window-color-mode-health" : "ghost-target-window-color-mode-department";
            ViewModeButton.Text = Loc.GetString(key);
            ViewModeButton.TooltipSupplier = _ => new Tooltip { Text = Loc.GetString("ghost-target-window-color-mode-tooltip") };
        }

        private void ToggleGroupMode(BaseButton.ButtonEventArgs _)
        {
            _separateGroups = !_separateGroups;
            UpdateGroupModeButtonText();
            var scroll = GhostScroll.GetScrollValue();
            Populate();
            GhostScroll.SetScrollValue(scroll);
        }

        private void UpdateGroupModeButtonText()
        {
            var key = _separateGroups ? "ghost-target-window-group-mode-separate" : "ghost-target-window-group-mode-together";
            GroupModeButton.Text = Loc.GetString(key);
            GroupModeButton.TooltipSupplier = _ => new Tooltip { Text = Loc.GetString("ghost-target-window-group-mode-tooltip") };
        }

        private static Color DimForDisplay(Color color, float factor = 0.78f)
        {
            return new Color(color.R * factor, color.G * factor, color.B * factor, color.A);
        }

        private static Color LightenForHover(Color color, float factor = 1.2f)
        {
            return new Color(
                Math.Min(1f, color.R * factor),
                Math.Min(1f, color.G * factor),
                Math.Min(1f, color.B * factor),
                color.A);
        }

        public void UpdateObserverCount(NetEntity entity, int count)
        {
            for (var i = 0; i < _warps.Count; i++)
            {
                if (_warps[i].Entity != entity)
                    continue;
                var (rawName, _, type, _, jobIconId, mobState, professionTitle, healthState, departmentId, groupId) = _warps[i];
                _warps[i] = (rawName, entity, type, count, jobIconId, mobState, professionTitle, healthState, departmentId, groupId);
                if (_entityToChip.TryGetValue(entity, out var state))
                {
                    state.NameLabel.Text = rawName;
                    state.ObserverCountLabel.Text = count.ToString();
                    state.ObserverBlock.Visible = count > 0;
                }
                return;
            }
        }

        public void Populate()
        {
            if (SearchBar.Text != _searchText)
                SearchBar.SetText(_searchText);

            _entityToChip.Clear();
            SectionsContainer.DisposeAllChildren();

            foreach (var type in SectionOrder)
            {
                var titleKey = SectionTitleKeys[(int) type];
                var count = _warps.Count(w => w.Type == type);
                var wrap = new PirateWrapContainer { SeparationOverride = 6, HorizontalExpand = true };

                var headingText = $"{Loc.GetString(titleKey)} ({count})";
                var section = new FramedCollapsible(headingText)
                {
                    Expanded = _sectionExpandedState.GetValueOrDefault(type, true),
                    IsEmptySection = count == 0,
                };
                section.OnToggled += expanded =>
                {
                    _sectionExpandedState[type] = expanded;
                };
                // CollapsibleBody does not stack its contents.
                var sectionContent = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 0, HorizontalExpand = true };
                sectionContent.AddChild(wrap);
                section.Body.AddChild(sectionContent);
                SectionsContainer.AddChild(section);

                var groups = new Dictionary<string, PirateWrapContainer>();
                foreach (var warp in _warps)
                {
                    if (warp.Type != type)
                        continue;

                    var chip = CreateChip(warp.RawName, warp.Entity, warp.ObserverCount, warp.JobIconId, warp.ProfessionTitle, warp.HealthState, warp.DepartmentId, warp.GroupId);

                    if (_separateGroups && type == GhostWarpType.Player && !string.IsNullOrEmpty(warp.GroupId))
                    {
                        if (!groups.TryGetValue(warp.GroupId, out var groupWrap))
                        {
                            groupWrap = new PirateWrapContainer { SeparationOverride = 6, HorizontalExpand = true };
                            groups[warp.GroupId] = groupWrap;
                        }

                        groupWrap.AddChild(chip);
                        continue;
                    }

                    wrap.AddChild(chip);
                }

                if (groups.Count > 0)
                    AddGroupSections(sectionContent, groups);
            }
        }

        private void AddGroupSections(BoxContainer parent, Dictionary<string, PirateWrapContainer> groups)
        {
            var ordered = groups
                .Select(kv => (Id: kv.Key, Wrap: kv.Value, Proto: PrototypeManager.TryIndex<GhostWarpGroupPrototype>(kv.Key, out var proto) ? proto : null))
                .OrderBy(g => g.Proto?.Priority ?? int.MaxValue)
                .ThenBy(g => g.Id, StringComparer.Ordinal);

            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = GroupTitleGapAbove,
                HorizontalExpand = true,
                Margin = new Thickness(0, GroupTitleGapAbove, 0, 0),
            };

            foreach (var (id, groupWrap, proto) in ordered)
            {
                var name = proto != null ? Loc.GetString(proto.Name) : id;
                var header = new Label
                {
                    Text = $"{name} ({groupWrap.ChildCount})",
                    FontColorOverride = GroupHeaderTextColor,
                    ClipText = true,
                };

                var group = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    SeparationOverride = GroupTitleGapBelow,
                    HorizontalExpand = true,
                };
                group.AddChild(header);
                group.AddChild(groupWrap);
                container.AddChild(group);
            }

            parent.AddChild(container);
        }

        private ContainerButton CreateChip(string rawName, NetEntity warpTarget, int observerCount, string? jobIconId, string? professionTitle, GhostWarpHealthState healthState, string? departmentId, string? groupId)
        {
            var bgColor = GetDisplayColor(_viewMode, healthState, professionTitle ?? string.Empty, departmentId ?? string.Empty, jobIconId, groupId);
            var entity = warpTarget;

            var styleBox = LoadoutStyles.RoundedFilled(bgColor, padding: 0f, patchMargin: 5f);
            styleBox.SetContentMarginOverride(StyleBox.Margin.Left, 4);
            styleBox.SetContentMarginOverride(StyleBox.Margin.Right, 6);
            styleBox.SetContentMarginOverride(StyleBox.Margin.Top, 2);
            styleBox.SetContentMarginOverride(StyleBox.Margin.Bottom, 2);

            var chip = new ContainerButton
            {
                StyleBoxOverride = styleBox,
                ModulateSelfOverride = Color.White,
                MinSize = new Vector2(0, 26),
            };
            chip.OnMouseEntered += _ =>
            {
                if (_entityToChip.TryGetValue(entity, out var s))
                {
                    styleBox.Modulate = LightenForHover(GetDisplayColor(_viewMode, s.HealthState, s.ProfessionTitle, s.DepartmentId, s.JobIconId, s.GroupId));
                }
            };
            chip.OnMouseExited += _ =>
            {
                if (_entityToChip.TryGetValue(entity, out var s))
                {
                    styleBox.Modulate = GetDisplayColor(_viewMode, s.HealthState, s.ProfessionTitle, s.DepartmentId, s.JobIconId, s.GroupId);
                }
            };

            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
            };

            if (!string.IsNullOrEmpty(jobIconId) && PrototypeManager.TryIndex<JobIconPrototype>(jobIconId, out var jobIcon))
            {
                try
                {
                    var texture = SpriteSystem.Frame0(jobIcon.Icon);
                    var iconWrapper = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Vertical,
                        MinSize = new Vector2(24, 0),
                        VerticalExpand = true,
                    };
                    var iconRect = new TextureRect
                    {
                        Texture = texture,
                        HorizontalExpand = true,
                        VerticalExpand = true,
                        Stretch = TextureRect.StretchMode.KeepAspectCentered,
                        CanShrink = true,
                    };
                    iconWrapper.AddChild(iconRect);
                    content.AddChild(iconWrapper);
                }
                catch { }
            }

            var nameLabel = new Label
            {
                Text = rawName,
                VerticalAlignment = VAlignment.Center,
                ClipText = false,
                HorizontalExpand = true,
            };
            content.AddChild(nameLabel);

            var observerBlock = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 2,
                VerticalAlignment = VAlignment.Center,
                Visible = observerCount > 0,
            };
            var observerIcon = new TextureRect
            {
                TexturePath = ObserverIconPath,
                MinSize = new Vector2(IconSize, IconSize),
                MaxSize = new Vector2(IconSize, IconSize),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                VerticalAlignment = VAlignment.Center,
            };
            observerBlock.AddChild(observerIcon);
            var observerCountLabel = new Label
            {
                Text = observerCount.ToString(),
                VerticalAlignment = VAlignment.Center,
                ClipText = false,
            };
            observerBlock.AddChild(observerCountLabel);
            content.AddChild(observerBlock);

            chip.AddChild(content);
            chip.OnPressed += _ => WarpClicked?.Invoke(warpTarget);
            if (!string.IsNullOrEmpty(professionTitle))
                chip.TooltipSupplier = _ => new Tooltip { Text = professionTitle };
            chip.Visible = ButtonIsVisible(rawName, professionTitle, departmentId);
            _entityToChip[warpTarget] = new ChipState(chip, styleBox, nameLabel, observerBlock, observerCountLabel, professionTitle ?? string.Empty, healthState, departmentId ?? string.Empty, jobIconId ?? string.Empty, groupId ?? string.Empty);
            return chip;
        }

        private bool ButtonIsVisible(string? displayName, string? professionTitle, string? departmentId)
        {
            if (string.IsNullOrWhiteSpace(_searchText))
                return true;
            var query = _searchText.Trim();
            if (displayName != null && displayName.Contains(query, StringComparison.OrdinalIgnoreCase))
                return true;
            if (professionTitle != null && professionTitle.Contains(query, StringComparison.OrdinalIgnoreCase))
                return true;
            if (!string.IsNullOrWhiteSpace(departmentId))
            {
                if (departmentId.Contains(query, StringComparison.OrdinalIgnoreCase))
                    return true;
                if (PrototypeManager.TryIndex<DepartmentPrototype>(departmentId, out var dept))
                {
                    var departmentName = Loc.GetString(dept.Name);
                    if (departmentName.Contains(query, StringComparison.OrdinalIgnoreCase))
                        return true;
                }
            }
            return false;
        }

        private void UpdateVisibleButtons()
        {
            foreach (var state in _entityToChip.Values)
                state.Chip.Visible = ButtonIsVisible(state.NameLabel.Text, state.ProfessionTitle, state.DepartmentId);
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text;
            UpdateVisibleButtons();
            GhostScroll.SetScrollValue(Vector2.Zero);
        }
    }
}
