// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client.GameTicking.Managers;
using Content.Client.UserInterface.Controls;
using Content.Shared._Pirate.NanoChatMonitor;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Pirate.NanoChatMonitor;

/// <summary>
///     Holds no history of its own: it pulls pages from the server as the reader scrolls.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NanoChatMonitorWindow : FancyWindow
{
    private static readonly TimeSpan SeparatorGap = TimeSpan.FromMinutes(1);
    private static readonly Color SeparatorLineColor = Color.FromHex("#50597844");
    private static readonly Color SeparatorTextColor = Color.FromHex("#9ca6c2");

    private const float ScrollEdgeSlack = 24f;

    public event Action<ulong, int, bool>? OnRequestPage;

    public event Action<string>? OnRequestAttachment;

    public event Action<string>? OnPrintPhoto;

    public event Action<ulong>? OnPrintLog;

    private readonly ClientGameTicker _gameTicker;

    private readonly List<NanoChatMonitorConversationSummary> _conversations = new();
    private readonly List<NanoChatMonitorConversationEntry> _conversationEntries = new();

    private readonly Dictionary<int, NanoChatMonitorLogEntry> _loaded = new();

    private ulong? _selectedKey;
    private uint _leftNumber;
    private int _loadedStart;
    private int _loadedEnd;
    private int _totalCount;

    private bool _awaitingPage;

    private float? _prependAnchorHeight;

    private bool _scrollToBottom;

    private bool _stickToBottom;

    private readonly Dictionary<string, NanoChatMonitorAttachmentMessage> _attachments = new();

    private readonly HashSet<string> _requestedAttachments = new();

    private readonly List<NanoChatMonitorMessageRow> _rows = new();

    public NanoChatMonitorWindow()
    {
        RobustXamlLoader.Load(this);

        _gameTicker = IoCManager.Resolve<IEntityManager>().System<ClientGameTicker>();

        SearchBar.OnTextChanged += _ => RebuildConversationList();
        LatestButton.OnPressed += _ => RequestLatest();
        PrintLogButton.OnPressed += _ =>
        {
            if (_selectedKey is { } key)
                OnPrintLog?.Invoke(key);
        };
    }

    public void UpdateState(NanoChatMonitorUiState state)
    {
        ScopeLabel.Text = Loc.GetString(state.Global
            ? "nanochat-monitor-scope-global"
            : "nanochat-monitor-scope-local");

        _conversations.Clear();
        _conversations.AddRange(state.Conversations);

        RebuildConversationList();

        if (_selectedKey is not { } selected)
            return;

        var summary = _conversations.Find(c => c.Key == selected);
        if (summary.Key != selected)
            return;

        var previousTotal = _totalCount;
        _totalCount = summary.MessageCount;
        UpdateCountLabel();

        if (_totalCount == previousTotal || _loadedEnd < previousTotal)
            return;

        _stickToBottom = IsScrolledToBottom();
        RequestPage(Math.Max(0, _totalCount - NanoChatMonitorConstants.PageSize));
    }

    #region Conversation list

    private void RebuildConversationList()
    {
        var filter = SearchBar.Text.Trim().ToLowerInvariant();

        ConversationList.RemoveAllChildren();
        _conversationEntries.Clear();

        var shown = 0;

        foreach (var summary in _conversations)
        {
            if (filter.Length > 0 &&
                !NanoChatMonitorConversationEntry.BuildSearchText(summary).Contains(filter, StringComparison.Ordinal))
                continue;

            var entry = new NanoChatMonitorConversationEntry();
            entry.Update(summary, GetStationTime(summary.LastTimestamp), _selectedKey == summary.Key);
            entry.OnPressed += _ => SelectConversation(summary.Key);

            ConversationList.AddChild(entry);
            _conversationEntries.Add(entry);
            shown++;
        }

        NoConversationsLabel.Visible = shown == 0;
        NoConversationsLabel.Text = Loc.GetString(_conversations.Count == 0
            ? "nanochat-monitor-no-conversations"
            : "nanochat-monitor-no-matches");
    }

    private void SelectConversation(ulong key)
    {
        _selectedKey = key;

        foreach (var entry in _conversationEntries)
        {
            entry.SetSelected(entry.ConversationKey == key);
        }

        var summary = _conversations.Find(c => c.Key == key);

        HeaderLabel.Text = Loc.GetString("nanochat-monitor-conversation-header",
            ("first", $"{summary.NameA} (#{summary.NumberA:D4})"),
            ("second", $"{summary.NameB} (#{summary.NumberB:D4})"));

        _leftNumber = summary.NumberA;
        _totalCount = summary.MessageCount;

        _loaded.Clear();
        _loadedStart = 0;
        _loadedEnd = 0;

        UpdateCountLabel();
        RequestLatest();
    }

    #endregion

    #region Loading

    private void RequestLatest()
    {
        if (_selectedKey is not { } key)
            return;

        _awaitingPage = true;
        OnRequestPage?.Invoke(key, 0, true);
    }

    private void RequestPage(int start)
    {
        if (_selectedKey is not { } key)
            return;

        _awaitingPage = true;
        OnRequestPage?.Invoke(key, start, false);
    }

    public void HandlePage(NanoChatMonitorPageMessage message)
    {
        _awaitingPage = false;

        if (_selectedKey != message.ConversationKey)
            return;

        _totalCount = message.TotalCount;

        var pageStart = message.StartIndex;
        var pageEnd = pageStart + message.Entries.Count;
        var oldStart = _loadedStart;
        var oldEnd = _loadedEnd;

        var contiguous = oldEnd > oldStart && pageStart <= oldEnd && pageEnd >= oldStart;

        if (contiguous)
        {
            _loadedStart = Math.Min(oldStart, pageStart);
            _loadedEnd = Math.Max(oldEnd, pageEnd);
        }
        else
        {
            _loaded.Clear();
            _loadedStart = pageStart;
            _loadedEnd = pageEnd;
        }

        for (var i = 0; i < message.Entries.Count; i++)
        {
            _loaded[pageStart + i] = message.Entries[i];
        }

        if (!contiguous)
            _scrollToBottom = _loadedEnd >= _totalCount;
        else if (_loadedStart < oldStart)
            _prependAnchorHeight = MessageList.Height;
        else if (_stickToBottom)
            _scrollToBottom = true;

        _stickToBottom = false;

        Rebuild();
    }

    private void Rebuild()
    {
        MessageList.RemoveAllChildren();
        _rows.Clear();

        TimeSpan? previousTime = null;
        uint? previousSender = null;

        for (var i = _loadedStart; i < _loadedEnd; i++)
        {
            if (!_loaded.TryGetValue(i, out var entry))
                continue;

            var stationTime = GetStationTime(entry.Timestamp);

            if (previousTime == null || stationTime - previousTime.Value >= SeparatorGap)
            {
                AddTimeSeparator(stationTime);

                previousSender = null;
            }

            var row = new NanoChatMonitorMessageRow();
            row.Update(entry, entry.SenderNumber != _leftNumber, previousSender != entry.SenderNumber);
            row.OnPrintPhoto += id => OnPrintPhoto?.Invoke(id);
            MessageList.AddChild(row);
            _rows.Add(row);

            if (entry.AttachmentId is { } attachmentId)
                LoadAttachment(row, attachmentId);

            previousTime = stationTime;
            previousSender = entry.SenderNumber;
        }

        UpdateCountLabel();
        MessageList.InvalidateMeasure();
        MessageScroll.InvalidateMeasure();
    }

    private void LoadAttachment(NanoChatMonitorMessageRow row, string attachmentId)
    {
        if (_attachments.TryGetValue(attachmentId, out var cached))
        {
            row.SetPhoto(cached);
            return;
        }

        if (!_requestedAttachments.Add(attachmentId))
            return;

        OnRequestAttachment?.Invoke(attachmentId);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_scrollToBottom)
        {
            MessageScroll.SetScrollValue(new Vector2(0, float.MaxValue));
            _scrollToBottom = false;
        }
        else if (_prependAnchorHeight is { } anchor)
        {
            var grew = MessageList.Height - anchor;
            if (grew > 0)
                MessageScroll.VScroll += grew;

            _prependAnchorHeight = null;
        }

        LatestButton.Visible = _selectedKey != null && !_awaitingPage && _loadedEnd < _totalCount;

        if (_selectedKey == null || _awaitingPage || _prependAnchorHeight != null || _scrollToBottom)
            return;

        if (MessageScroll.VScroll <= ScrollEdgeSlack && _loadedStart > 0)
            RequestPage(Math.Max(0, _loadedStart - NanoChatMonitorConstants.PageSize));
        else if (IsScrolledToBottom() && _loadedEnd < _totalCount)
            RequestPage(_loadedEnd);
    }

    private bool IsScrolledToBottom()
    {
        var viewport = MessageScroll.Height;
        var content = MessageList.Height;

        return content <= viewport || MessageScroll.VScroll + viewport >= content - ScrollEdgeSlack;
    }

    private void UpdateCountLabel()
    {
        CountLabel.Text = _selectedKey == null
            ? string.Empty
            : Loc.GetString("nanochat-monitor-message-count", ("count", _totalCount));

        PrintLogButton.Visible = _selectedKey != null && _totalCount > 0;
    }

    private void AddTimeSeparator(TimeSpan stationTime)
    {
        MessageList.AddChild(new Control { MinSize = new Vector2(0, 6) });

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        row.AddChild(MakeSeparatorLine());
        row.AddChild(new Label
        {
            Text = stationTime.ToString(@"hh\:mm\:ss"),
            Margin = new Thickness(12, 0, 12, 0),
            StyleClasses = { "LabelSubText" },
            ModulateSelfOverride = SeparatorTextColor,
        });
        row.AddChild(MakeSeparatorLine());

        MessageList.AddChild(row);
        MessageList.AddChild(new Control { MinSize = new Vector2(0, 6) });
    }

    private static PanelContainer MakeSeparatorLine()
    {
        return new PanelContainer
        {
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            MinSize = new Vector2(0, 1),
            MaxSize = new Vector2(float.MaxValue, 1),
            PanelOverride = new StyleBoxFlat { BackgroundColor = SeparatorLineColor },
        };
    }

    private TimeSpan GetStationTime(TimeSpan timestamp)
    {
        var stationTime = timestamp - _gameTicker.RoundStartTimeSpan;
        return stationTime < TimeSpan.Zero ? TimeSpan.Zero : stationTime;
    }

    #endregion

    #region Attachments

    public void HandleAttachment(NanoChatMonitorAttachmentMessage message)
    {
        _attachments[message.AttachmentId] = message;

        foreach (var row in _rows)
        {
            row.SetPhoto(message);
        }
    }

    #endregion
}
