// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Text;
using Content.Shared._Pirate.NanoChatMonitor;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.NanoChatMonitor;

[GenerateTypedNameReferences]
public sealed partial class NanoChatMonitorConversationEntry : ContainerButton
{
    private static readonly Color SelectedEntryColor = Color.FromHex("#4d5478d9");
    private static readonly Color ActiveIndicatorColor = Color.FromHex("#7ea2ff");

    private const int NameMaxChars = 16;

    private const int LineMaxChars = 36;

    public ulong ConversationKey { get; private set; }

    public NanoChatMonitorConversationEntry()
    {
        RobustXamlLoader.Load(this);
    }

    public static string BuildSearchText(NanoChatMonitorConversationSummary summary)
    {
        var builder = new StringBuilder();

        builder.Append(summary.NameA);
        builder.Append(' ');
        builder.Append(summary.NameB);
        builder.Append(' ');
        builder.Append(summary.JobA);
        builder.Append(' ');
        builder.Append(summary.JobB);
        builder.Append(' ');
        builder.Append($"{summary.NumberA:D4}");
        builder.Append(' ');
        builder.Append($"{summary.NumberB:D4}");
        builder.Append(' ');
        builder.Append(summary.NumberA);
        builder.Append(' ');
        builder.Append(summary.NumberB);

        return builder.ToString().ToLowerInvariant();
    }

    public void Update(NanoChatMonitorConversationSummary summary, TimeSpan lastStationTime, bool selected)
    {
        ConversationKey = summary.Key;

        Describe(FirstParticipantLabel, summary.NameA, summary.JobA, summary.NumberA);
        Describe(SecondParticipantLabel, summary.NameB, summary.JobB, summary.NumberB);

        TimeLabel.Text = Loc.GetString("nanochat-monitor-conversation-last",
            ("time", lastStationTime.ToString(@"hh\:mm\:ss")));

        SetSelected(selected);
    }

    public void SetSelected(bool selected)
    {
        Pressed = selected;
        ModulateSelfOverride = selected ? SelectedEntryColor : null;

        if (SelectionIndicator.PanelOverride is not StyleBoxFlat indicator)
            return;

        var color = selected ? ActiveIndicatorColor : Color.Transparent;
        indicator.BackgroundColor = color;
        indicator.BorderColor = color;
    }

    private static void Describe(RichTextLabel label, string name, string? job, uint number)
    {
        var number4 = $"{number:D4}";

        var full = string.IsNullOrWhiteSpace(job)
            ? Loc.GetString("nanochat-monitor-conversation-participant", ("name", name), ("number", number4))
            : Loc.GetString("nanochat-monitor-conversation-participant-job",
                ("name", name),
                ("number", number4),
                ("job", job));

        var shortened = string.IsNullOrWhiteSpace(job)
            ? Loc.GetString("nanochat-monitor-conversation-participant",
                ("name", Truncate(name, NameMaxChars)),
                ("number", number4))
            : Loc.GetString("nanochat-monitor-conversation-participant-job",
                ("name", Truncate(name, NameMaxChars)),
                ("number", number4),
                ("job", job));

        label.Text = Truncate(shortened, LineMaxChars);
        label.ToolTip = full;
    }

    private static string Truncate(string text, int maxChars)
    {
        return text.Length <= maxChars ? text : text[..(maxChars - 1)] + "…";
    }
}
