using System.Collections.Generic;
using System.Linq;
using System.Text;
using Content.Client.Administration.Managers;
using Content.Client.Administration.Systems;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Network;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.Bwoink
{
    [GenerateTypedNameReferences]
    public sealed partial class CreateGroupDialog : DefaultWindow
    {
        private readonly HashSet<NetUserId> _selectedPlayers = new();
        private readonly AdminSystem _adminSystem;
        private readonly IClientAdminManager _adminManager;

        public CreateGroupDialog()
        {
            RobustXamlLoader.Load(this);
            _adminSystem = IoCManager.Resolve<IEntityManager>().System<AdminSystem>();
            _adminManager = IoCManager.Resolve<IClientAdminManager>();

            // Pirate Changes Start Here - Check admin permissions
            if (!_adminManager.HasFlag(AdminFlags.Adminhelp))
            {
                Close();
                return;
            }
            // Pirate Changes End Here

            // Initialize player selector
            PlayerSelector.PopulateList(_adminSystem.PlayerList);
            PlayerSelector.OnSelectionChanged += OnPlayerSelected;

            // Setup buttons
            CreateButton.OnPressed += OnCreatePressed;
            CancelButton.OnPressed += OnCancelPressed;

            // Initialize with empty selection
            UpdateSelectedPlayersDisplay();
        }

        private void OnPlayerSelected(PlayerInfo? player)
        {
            if (player == null)
                return;

            if (_selectedPlayers.Contains(player.SessionId))
            {
                _selectedPlayers.Remove(player.SessionId);
            }
            else
            {
                _selectedPlayers.Add(player.SessionId);
            }

            UpdateSelectedPlayersDisplay();
        }

        private void UpdateSelectedPlayersDisplay()
        {
            var sb = new StringBuilder();
            var playerList = _adminSystem.PlayerList;

            foreach (var playerId in _selectedPlayers)
            {
                var player = playerList.FirstOrDefault(p => p.SessionId == playerId);
                if (player != null)
                {
                    if (sb.Length > 0)
                        sb.AppendLine();
                    sb.Append($"• {player.CharacterName} ({player.Username})");
                }
            }

            if (sb.Length == 0)
                sb.Append(Loc.GetString("create-group-dialog-no-players-selected"));

            var message = new FormattedMessage();
            message.AddText(sb.ToString());
            SelectedPlayersLabel.SetMessage(message);

            // Enable/disable create button based on selection
            CreateButton.Disabled = string.IsNullOrWhiteSpace(GroupNameEdit.Text) || _selectedPlayers.Count == 0;
        }

        private void OnCreatePressed(BaseButton.ButtonEventArgs args)
        {
            var groupName = GroupNameEdit.Text?.Trim();
            if (string.IsNullOrWhiteSpace(groupName) || _selectedPlayers.Count == 0)
                return;

            // Create the group
            var bwoinkSystem = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
            bwoinkSystem.CreateGroup(groupName, _selectedPlayers.ToList());

            Close();
        }

        private void OnCancelPressed(BaseButton.ButtonEventArgs args)
        {
            Close();
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            GroupNameEdit.OnTextChanged += OnGroupNameChanged;
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            GroupNameEdit.OnTextChanged -= OnGroupNameChanged;
        }

        private void OnGroupNameChanged(LineEdit.LineEditEventArgs args)
        {
            UpdateSelectedPlayersDisplay();
        }
    }
}
