using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.Administration.Managers;
using Content.Client.Administration.Systems;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Network;

namespace Content.Client.Administration.UI.Bwoink
{
    [GenerateTypedNameReferences]
    public sealed partial class ManageGroupDialog : DefaultWindow
    {
        private readonly Guid _groupId;
        private readonly BwoinkGroupInfo _groupInfo;
        private readonly AdminSystem _adminSystem;
        private readonly IClientAdminManager _adminManager;
        private PlayerInfo? _selectedPlayerToAdd;
        private PlayerInfo? _selectedMemberToMute;

        public ManageGroupDialog(Guid groupId, BwoinkGroupInfo groupInfo)
        {
            RobustXamlLoader.Load(this);

            _groupId = groupId;
            _groupInfo = groupInfo;
            _adminSystem = IoCManager.Resolve<IEntityManager>().System<AdminSystem>();
            _adminManager = IoCManager.Resolve<IClientAdminManager>();

            // Pirate Changes Start Here - Check admin permissions
            if (!_adminManager.HasFlag(AdminFlags.Adminhelp))
            {
                Close();
                return;
            }
            // Pirate Changes End Here

            // Initialize UI
            GroupNameEdit.Text = groupInfo.GroupName;
            Title = Loc.GetString("manage-group-dialog-title", ("groupName", groupInfo.GroupName));

            // Setup player selector with players not in the group
            var availablePlayers = _adminSystem.PlayerList
                .Where(p => !groupInfo.Members.Contains(p.SessionId))
                .ToList();
            PlayerSelector.PopulateList(availablePlayers);

            // Setup event handlers
            RenameButton.OnPressed += OnRenamePressed;
            AddPlayerButton.OnPressed += OnAddPlayerPressed;
            DeleteGroupButton.OnPressed += OnDeleteGroupPressed;
            CloseDialogButton.OnPressed += OnClosePressed;
            MuteButton.OnPressed += OnMutePressed;
            UnmuteButton.OnPressed += OnUnmutePressed;

            // Subscribe to player selection changes
            PlayerSelector.OnSelectionChanged += OnPlayerSelectionChanged;

            // Setup mute duration options
            SetupMuteDurationOptions();

            // Populate members list
            UpdateMembersList();
        }

        private void OnPlayerSelectionChanged(PlayerInfo? selectedPlayer)
        {
            _selectedPlayerToAdd = selectedPlayer;
        }

        private void UpdateMembersList()
        {
            MembersList.RemoveAllChildren();

            foreach (var memberId in _groupInfo.Members)
            {
                var player = _adminSystem.PlayerList.FirstOrDefault(p => p.SessionId == memberId);
                if (player == null)
                    continue;

                var memberContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true
                };

                var memberButton = new Button
                {
                    Text = $"{player.CharacterName} ({player.Username})",
                    HorizontalExpand = true,
                    ToggleMode = true
                };

                memberButton.OnPressed += _ =>
                {
                    // Deselect other member buttons
                    foreach (var child in MembersList.Children)
                    {
                        if (child is BoxContainer container)
                        {
                            foreach (var subChild in container.Children)
                            {
                                if (subChild is Button btn && btn != memberButton && btn.ToggleMode)
                                {
                                    btn.Pressed = false;
                                }
                            }
                        }
                    }

                    if (memberButton.Pressed)
                    {
                        OnMemberSelected(player);
                    }
                    else
                    {
                        OnMemberSelected(null);
                    }
                };

                var removeButton = new Button
                {
                    Text = Loc.GetString("manage-group-dialog-remove"),
                    MinWidth = 80
                };

                var currentMemberId = memberId; // Capture for closure
                removeButton.OnPressed += _ => OnRemovePlayerPressed(currentMemberId);

                memberContainer.AddChild(memberButton);
                memberContainer.AddChild(removeButton);
                MembersList.AddChild(memberContainer);
            }
        }

        private void OnRenamePressed(BaseButton.ButtonEventArgs args)
        {
            var newName = GroupNameEdit.Text?.Trim();
            if (string.IsNullOrWhiteSpace(newName) || newName == _groupInfo.GroupName)
                return;

            // Pirate Changes Start Here - Implement group rename functionality
            var bwoinkSystem = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
            bwoinkSystem.RenameGroup(_groupInfo.GroupId, newName);

            // Update local display
            Title = Loc.GetString("manage-group-dialog-title", ("groupName", newName));
            // Pirate Changes End Here
        }

        private void OnAddPlayerPressed(BaseButton.ButtonEventArgs args)
        {
            if (_selectedPlayerToAdd == null)
                return;

            var bwoinkSystem = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
            bwoinkSystem.AddToGroup(_groupId, _selectedPlayerToAdd.SessionId);

            // Update the available players list
            var availablePlayers = _adminSystem.PlayerList
                .Where(p => !_groupInfo.Members.Contains(p.SessionId) && p.SessionId != _selectedPlayerToAdd.SessionId)
                .ToList();
            PlayerSelector.PopulateList(availablePlayers);
        }

        private void OnRemovePlayerPressed(NetUserId playerId)
        {
            var bwoinkSystem = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
            bwoinkSystem.RemoveFromGroup(_groupId, playerId);
        }

        private void OnDeleteGroupPressed(BaseButton.ButtonEventArgs args)
        {
            var bwoinkSystem = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
            bwoinkSystem.DeleteGroup(_groupId);
            Close();
        }

        private void OnClosePressed(BaseButton.ButtonEventArgs args)
        {
            Close();
        }

        private void SetupMuteDurationOptions()
        {
            MuteDurationButton.AddItem(Loc.GetString("mute-duration-5min"), 0);
            MuteDurationButton.AddItem(Loc.GetString("mute-duration-15min"), 1);
            MuteDurationButton.AddItem(Loc.GetString("mute-duration-30min"), 2);
            MuteDurationButton.AddItem(Loc.GetString("mute-duration-1hour"), 3);
            MuteDurationButton.SelectId(0);
        }

        private void OnMutePressed(BaseButton.ButtonEventArgs args)
        {
            if (_selectedMemberToMute == null)
                return;

            var duration = MuteDurationButton.SelectedId switch
            {
                0 => TimeSpan.FromMinutes(5),
                1 => TimeSpan.FromMinutes(15),
                2 => TimeSpan.FromMinutes(30),
                3 => TimeSpan.FromHours(1),
                _ => TimeSpan.FromMinutes(5)
            };

            var bwoinkSystem = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
            bwoinkSystem.MutePlayer(_selectedMemberToMute.SessionId, duration);
        }

        private void OnUnmutePressed(BaseButton.ButtonEventArgs args)
        {
            if (_selectedMemberToMute == null)
                return;

            var bwoinkSystem = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
            bwoinkSystem.UnmutePlayer(_selectedMemberToMute.SessionId);
        }

        private void OnMemberSelected(PlayerInfo? member)
        {
            _selectedMemberToMute = member;
            MuteButton.Disabled = member == null;
            UnmuteButton.Disabled = member == null;
        }
    }
}
