using Content.Client.UserInterface.Controls;
using Content.Pirate.Shared.ModularSuit;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Pirate.Client.ModularSuit.Ui;

[GenerateTypedNameReferences]
public sealed partial class LightModuleWindow : FancyWindow
{
    public event Action<Color, bool>? OnUpdate;

    public LightModuleWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmationButton.OnPressed += _ => Update();
    }

    public void UpdateState(LightModuleBoundUserInterfaceState state)
    {
        ColorSelector.Color = state.LightColor;
        MulticolouredCheckbox.Pressed = state.Multicoloured;
    }

    private void Update()
    {
        OnUpdate?.Invoke(ColorSelector.Color, MulticolouredCheckbox.Pressed);
    }
}
