# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Visitor
  name: job-name-visitor
  description: job-description-visitor
  playTimeTracker: JobVisitor
  # Pirate: skill chips start
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipTiderDampener
    - SkillChipEducation
  # Pirate: skill chips end
  canBeAntag: false
  icon: JobIconVisitor
  setPreference: false
  overrideConsoleVisibility: true
  access:
  - Maintenance
  extendedAccess:
  - External