// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using static Content.Shared.Access.Components.IdCardConsoleComponent;

namespace Content.Client.Access.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class IdCardConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly ILogManager _logManager = default!;
        private readonly ISawmill _logMill = default!;

        private readonly IdCardConsoleBoundUserInterface _owner;

        // CCVar.
        private int _maxNameLength;
        private int _maxIdJobLength;

        private AccessLevelControl _accessButtons = new();
        // Pirate start: add categories
        private readonly List<JobPrototype> _visibleJobs = new();
        private readonly List<IdCardJobCategoryPrototype> _jobCategories = new();
        // Pirate end
        private readonly List<string> _jobPrototypeIds = new();

        private string? _lastFullName;
        private string? _lastJobTitle;
        private string? _lastJobProto;

        // The job that will be picked if the ID doesn't have a job on the station.
        private static ProtoId<JobPrototype> _defaultJob = "Passenger";

        public IdCardConsoleWindow(IdCardConsoleBoundUserInterface owner, IPrototypeManager prototypeManager,
            List<ProtoId<AccessLevelPrototype>> accessLevels)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _logMill = _logManager.GetSawmill(SharedIdCardConsoleSystem.Sawmill);

            _owner = owner;

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);

            FullNameLineEdit.OnTextEntered += _ => SubmitData();
            FullNameLineEdit.IsValid = s => s.Length <= _maxNameLength;
            FullNameLineEdit.OnTextChanged += _ =>
            {
                FullNameSaveButton.Disabled = FullNameSaveButton.Text == _lastFullName;
            };
            FullNameSaveButton.OnPressed += _ => SubmitData();

            JobTitleLineEdit.OnTextEntered += _ => SubmitData();
            JobTitleLineEdit.IsValid = s => s.Length <= _maxIdJobLength;
            JobTitleLineEdit.OnTextChanged += _ =>
            {
                JobTitleSaveButton.Disabled = JobTitleLineEdit.Text == _lastJobTitle;
            };
            JobTitleSaveButton.OnPressed += _ => SubmitData();
            // Goobstation Start
            SearchLineEdit.OnTextChanged += args =>
            {
                var query = args.Text.Trim();
                var containerChild = AccessLevelControlContainer.GetChild(0);
                containerChild.RemoveAllChildren();

                if (string.IsNullOrEmpty(query))
                {
                    foreach (var button in _accessButtons.ButtonsList.Values)
                        containerChild.AddChild(button);
                    return;
                }

                foreach (var (id, button) in _accessButtons.ButtonsList)
                    if (id.Id.Contains(query, StringComparison.CurrentCultureIgnoreCase))
                        containerChild.AddChild(button);
            };
            // Goobstation End

            // Pirate start: add categories
            _visibleJobs.AddRange(_prototypeManager.EnumeratePrototypes<JobPrototype>()
                .Where(job => job.OverrideConsoleVisibility.GetValueOrDefault(job.SetPreference))
                .OrderBy(job => job.LocalizedName, StringComparer.CurrentCulture));
            _jobCategories.AddRange(_prototypeManager.EnumeratePrototypes<IdCardJobCategoryPrototype>()
                .Where(category => category.Jobs.Any(jobId => _visibleJobs.Any(job => job.ID == jobId.Id)))
                .OrderBy(category => Loc.GetString(category.Name), StringComparer.CurrentCulture));

            JobCategoryOptionButton.AddItem(Loc.GetString("id-card-console-window-job-category-general"), 0);
            JobCategoryOptionButton.SelectId(0);
            for (var i = 0; i < _jobCategories.Count; i++)
                JobCategoryOptionButton.AddItem(Loc.GetString(_jobCategories[i].Name), i + 1);

            PopulateJobPresets(0, _defaultJob.Id);
            JobCategoryOptionButton.OnItemSelected += SelectJobCategory;
            // Pirate end

            SelectAllButton.OnPressed += _ =>
            {
                SetAllAccess(true);
                SubmitData();
            };

            DeselectAllButton.OnPressed += _ =>
            {
                SetAllAccess(false);
                SubmitData();
            };

            JobPresetOptionButton.OnItemSelected += SelectJobPreset;
            _accessButtons.Populate(accessLevels, prototypeManager);
            AccessLevelControlContainer.AddChild(_accessButtons);

            foreach (var (id, button) in _accessButtons.ButtonsList)
            {
                button.OnToggled += args => _owner.SetAccess(id, args.Pressed); // id card console fix
            }
        }

        /// <param name="enabled">If true, every individual access button will be pressed. If false, each will be depressed.</param>
        private void SetAllAccess(bool enabled)
        {
            foreach (var button in _accessButtons.ButtonsList.Values)
            {
                if (!button.Disabled && button.Pressed != enabled)
                    button.Pressed = enabled;
            }
        }

        private void SelectJobPreset(OptionButton.ItemSelectedEventArgs args)
        {
            if (args.Id < 0 || args.Id >= _jobPrototypeIds.Count) // Pirate add categories
                return;

            if (!_prototypeManager.TryIndex(_jobPrototypeIds[args.Id], out JobPrototype? job))
            {
                return;
            }

            JobTitleLineEdit.Text = Loc.GetString(job.Name);
            _lastJobProto = job.ID;// Pirate add categories
            args.Button.SelectId(args.Id);

            // Pirate start: add categories
            var categoryIndex = _jobCategories.FindIndex(category => category.Jobs.Contains(job.ID));
            JobCategoryOptionButton.SelectId(categoryIndex < 0 ? 0 : categoryIndex + 1);
            // Pirate end

            SetAllAccess(false);

            // this is a sussy way to do this
            foreach (var access in job.Access)
            {
                if (_accessButtons.ButtonsList.TryGetValue(access, out var button) && !button.Disabled)
                {
                    button.Pressed = true;
                }
            }

            foreach (var group in job.AccessGroups)
            {
                if (!_prototypeManager.Resolve(group, out AccessGroupPrototype? groupPrototype))
                {
                    continue;
                }

                foreach (var access in groupPrototype.Tags)
                {
                    if (_accessButtons.ButtonsList.TryGetValue(access, out var button) && !button.Disabled)
                    {
                        button.Pressed = true;
                    }
                }
            }

            SubmitData(job.ID); // Pirate - add (job.ID)
        }

        public void UpdateState(IdCardConsoleBoundUserInterfaceState state)
        {
            PrivilegedIdButton.Text = state.IsPrivilegedIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            PrivilegedIdLabel.Text = state.PrivilegedIdName;

            TargetIdButton.Text = state.IsTargetIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            TargetIdLabel.Text = state.TargetIdName;

            var interfaceEnabled =
                state.IsPrivilegedIdPresent && state.IsPrivilegedIdAuthorized && state.IsTargetIdPresent;

            var fullNameDirty = _lastFullName != null && FullNameLineEdit.Text != state.TargetIdFullName;
            var jobTitleDirty = _lastJobTitle != null && JobTitleLineEdit.Text != state.TargetIdJobTitle;

            FullNameLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            FullNameLineEdit.Editable = interfaceEnabled;
            if (!fullNameDirty)
            {
                FullNameLineEdit.Text = state.TargetIdFullName ?? string.Empty;
            }

            FullNameSaveButton.Disabled = !interfaceEnabled || !fullNameDirty;

            JobTitleLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            JobTitleLineEdit.Editable = interfaceEnabled;
            if (!jobTitleDirty)
            {
                JobTitleLineEdit.Text = state.TargetIdJobTitle ?? string.Empty;
            }

            JobTitleSaveButton.Disabled = !interfaceEnabled || !jobTitleDirty;

            JobPresetOptionButton.Disabled = !interfaceEnabled;
            JobCategoryOptionButton.Disabled = !interfaceEnabled; // Pirate add categories

            _accessButtons.UpdateState(state.TargetIdAccessList?.ToList() ??
                                       new List<ProtoId<AccessLevelPrototype>>(),
                                       state.AllowedModifyAccessList?.ToList() ??
                                       new List<ProtoId<AccessLevelPrototype>>());

            // Pirate start: add categories
            var categoryIndex = _jobCategories.FindIndex(category => category.Jobs.Contains(state.TargetIdJobPrototype));
            categoryIndex = categoryIndex < 0 ? 0 : categoryIndex + 1;
            JobCategoryOptionButton.SelectId(categoryIndex);
            PopulateJobPresets(categoryIndex, state.TargetIdJobPrototype);
            // Pirate end

            _lastFullName = state.TargetIdFullName;
            _lastJobTitle = state.TargetIdJobTitle;
            _lastJobProto = state.TargetIdJobPrototype;
        }

        private void SubmitData(string jobPrototype = "") // Pirate
        {
            _owner.SubmitData(
                FullNameLineEdit.Text,
                JobTitleLineEdit.Text,
                // Iterate over the buttons dictionary, filter by `Pressed`, only get key from the key/value pair
                _accessButtons.ButtonsList.Where(x => x.Value.Pressed).Select(x => x.Key).ToList(),
                jobPrototype);
        }

        // Pirate start: add categories
        private void SelectJobCategory(OptionButton.ItemSelectedEventArgs args)
        {
            args.Button.SelectId(args.Id);
            PopulateJobPresets(args.Id, _lastJobProto);
        }

        private void PopulateJobPresets(int categoryIndex, string? preferredJob)
        {
            var categorizedJobs = _jobCategories.SelectMany(category => category.Jobs).ToHashSet();
            var jobs = categoryIndex == 0
                ? _visibleJobs.Where(job => !categorizedJobs.Contains(job.ID))
                : _visibleJobs.Where(job => _jobCategories[categoryIndex - 1].Jobs.Contains(job.ID));

            _jobPrototypeIds.Clear();
            JobPresetOptionButton.Clear();
            foreach (var job in jobs)
            {
                _jobPrototypeIds.Add(job.ID);
                JobPresetOptionButton.AddItem(Loc.GetString(job.Name), _jobPrototypeIds.Count - 1);
            }

            var selectedIndex = preferredJob == null ? -1 : _jobPrototypeIds.IndexOf(preferredJob);
            if (selectedIndex < 0)
                selectedIndex = _jobPrototypeIds.IndexOf(_defaultJob.Id);
            if (selectedIndex < 0 && _jobPrototypeIds.Count > 0)
                selectedIndex = 0;

            if (selectedIndex >= 0)
                JobPresetOptionButton.SelectId(selectedIndex);
        // Pirate end
        }
    }
}
