# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
  - !type:RoleTimeRequirement
    role: JobForensicMantis
    time: 18000 # 5 hours
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 6h # Goobstation
  - !type:DepartmentTimeRequirement
    department: Science
    time: 10h
  - !type:TraitsRequirement
    inverted: true
    traits:
    - DeafTrait
    - Blindness
    - Narcolepsy
    - Muted
    - WheelchairBound # Pirate end
  #- !type:SpeciesRequirement # Pirate remove requirement
  #  inverted: true
  #  species:
  #  - Felinid
  # Pirate contractor start
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
    - Interdyne
  # Pirate contractor end
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  #canBeAntag: false
  antagAdvantage: 75 # Goobstation
  guides: # goobstation
  - Science
  - Command
  - ResearchDirectorSOP
  - ScienceSOP
  goobcoins: 40 #Goob content
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  - External # Goobstation
  - Mantis # Pirate
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddPsionicComponentSpecial # Pirate: IPC insulation blocks direct-start psionics without banning the job.
    components:
      - type: Psionic # DeltaV - They start with telepathic chat.
      - type: DispelPower # DeltaV - They get the Dispel psionic power on spawn.

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetAltScience # Goobstation
  storage:
    back:
    - CosmicCenser # DeltaV - Cosmic Cult
    # Pirate: Flash and TelescopicBaton moved to loadouts.

- type: chameleonOutfit
  id: ResearchDirectorChameleonOutfit
  job: ResearchDirector
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretRND
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckCloakRd
    outerClothing: ClothingOuterCoatRD
    gloves: ClothingHandsGlovesColorPurple
