// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.StationRecords;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
#region Pirate: records photos
using Content.Client._Pirate.UserInterface.Controls;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Content.Shared._Pirate.Origin;
using Content.Shared._Pirate.Employment;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using System.Linq;
#endregion

namespace Content.Client.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class GeneralRecord : Control
{
    #region Pirate: records photos
    [Dependency] private readonly IEntityManager _entManager = default!;

    public Action<string, string, string, int, Gender>? OnIdentityInfoChanged;
    public Action<string, string>? OnForensicsInfoChanged;

    private readonly IPrototypeManager _proto;
    private readonly SpriteSystem _spriteSystem;
    private readonly List<SpeciesPrototype> _species = new();
    private readonly List<CitizenshipPrototype> _citizenships = new();
    private readonly List<EmployerPrototype> _employers = new();
    private HumanoidCharacterProfile? _recordProfile;
    private readonly uint _maxLength;
    private bool _suppressEvents;
    private bool _speciesUnset;
    private bool _citizenshipUnset;
    private bool _employerUnset;
    private bool _genderUnset;

    public GeneralRecord(GeneralStationRecord record, uint maxLength, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _proto = prototypeManager;
        _spriteSystem = _entManager.System<SpriteSystem>();
        _maxLength = maxLength;

        PopulateGenderOptions();
        RefreshSpeciesOptions();

        PersonPrintsEdit.IsValid = text => text.Length <= _maxLength;
        PersonDnaEdit.IsValid = text => text.Length <= _maxLength;

        SpeciesButton.OnItemSelected += args =>
        {
            if (_suppressEvents || _recordProfile == null)
                return;

            _speciesUnset = false;
            SpeciesButton.SelectId(args.Id);
            UpdateRecordIdentityProfile(_recordProfile.WithSpecies(_species[args.Id].ID), true);
        };

        CitizenshipButton.OnItemSelected += args =>
        {
            if (_suppressEvents || _recordProfile == null)
                return;

            _citizenshipUnset = false;
            CitizenshipButton.SelectId(args.Id);
            UpdateRecordIdentityProfile(_recordProfile.WithCitizenship(_citizenships[args.Id].ID), true);
        };

        EmployerButton.OnItemSelected += args =>
        {
            if (_suppressEvents || _recordProfile == null)
                return;

            _employerUnset = false;
            EmployerButton.SelectId(args.Id);
            UpdateRecordIdentityProfile(_recordProfile.WithEmployer(_employers[args.Id].ID), true);
        };

        GenderButton.OnItemSelected += args =>
        {
            if (_suppressEvents || _recordProfile == null)
                return;

            _genderUnset = false;
            GenderButton.SelectId(args.Id);
            UpdateRecordIdentityProfile(_recordProfile.WithGender((Gender) args.Id), true);
        };

        AgeEdit.OnTextEntered += args => CommitAgeEdit(args.Text);
        AgeEdit.OnFocusExit += args => CommitAgeEdit(args.Text);
        PersonPrintsEdit.OnTextEntered += args => CommitForensicsEdits(args.Text, PersonDnaEdit.Text);
        PersonPrintsEdit.OnFocusExit += args => CommitForensicsEdits(args.Text, PersonDnaEdit.Text);
        PersonDnaEdit.OnTextEntered += args => CommitForensicsEdits(PersonPrintsEdit.Text, args.Text);
        PersonDnaEdit.OnFocusExit += args => CommitForensicsEdits(PersonPrintsEdit.Text, args.Text);

        PopulateRecord(record);
    }

    private void PopulateRecord(GeneralStationRecord record)
    {
        var na = Loc.GetString("generic-not-available-shorthand");

        PersonName.Text = record.Name;
        PersonJob.Text = record.JobTitle ?? na;
        PersonJobIcon.Texture = null;

        if (_proto.TryIndex<JobIconPrototype>(record.JobIcon, out var proto))
            PersonJobIcon.Texture = _spriteSystem.Frame0(proto.Icon);

        PersonPrintsEdit.Text = record.Fingerprint ?? string.Empty;
        PersonDnaEdit.Text = record.DNA ?? string.Empty;

        UpdateRecordIdentityProfile(BuildRecordIdentityProfile(record), false, record);
    }

    private void RefreshSpeciesOptions()
    {
        _species.Clear();
        _species.AddRange(_proto.EnumeratePrototypes<SpeciesPrototype>()
            .Where(species => species.RoundStart)
            .OrderBy(species => Loc.GetString(species.Name)));
    }

    private void PopulateGenderOptions()
    {
        GenderButton.Clear();
        GenderButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int) Gender.Male);
        GenderButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int) Gender.Female);
        GenderButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int) Gender.Epicene);
        GenderButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int) Gender.Neuter);
    }

    private HumanoidCharacterProfile BuildRecordIdentityProfile(GeneralStationRecord record)
    {
        var profile = new HumanoidCharacterProfile
        {
            Species = string.Empty,
            Citizenship = string.Empty,
            Employer = string.Empty,
            Age = 0,
        }
            .WithName(record.Name)
            .WithGender(record.Gender);

        if (!string.IsNullOrWhiteSpace(record.Species))
            profile = profile.WithSpecies(record.Species);

        if (!string.IsNullOrWhiteSpace(record.Citizenship))
            profile = profile.WithCitizenship(record.Citizenship);

        if (!string.IsNullOrWhiteSpace(record.Employer))
            profile = profile.WithEmployer(record.Employer);

        if (record.Age > 0)
            profile = profile.WithAge(record.Age);

        return profile;
    }

    private void UpdateRecordIdentityProfile(HumanoidCharacterProfile profile, bool sendUpdate, GeneralStationRecord? rawRecord = null)
    {
        // Pirate: records photos
        _recordProfile = profile;

        if (rawRecord != null)
        {
            _speciesUnset = IsIdentitySelectorBlank(rawRecord.Species);
            _citizenshipUnset = IsIdentitySelectorBlank(rawRecord.Citizenship);
            _employerUnset = IsIdentitySelectorBlank(rawRecord.Employer);
            _genderUnset = _speciesUnset; // Гендер невстановлений, якщо вид невстановлений
        }

        _suppressEvents = true;
        try
        {
            PopulateSpeciesSelector(profile.Species, _speciesUnset);
            PopulateCitizenshipSelector(profile, _citizenshipUnset);
            PopulateEmployerSelector(profile, _employerUnset);

            if (_genderUnset)
                ApplyOptionButtonPlaceholder(GenderButton, Loc.GetString("generic-not-available-shorthand"));
            else
                GenderButton.SelectId((int) profile.Gender);

            AgeEdit.Text = rawRecord != null && rawRecord.Age <= 0
                ? string.Empty
                : profile.Age.ToString();
        }
        finally
        {
            _suppressEvents = false;
        }

        if (sendUpdate && !_speciesUnset && !_genderUnset) // Pirate: records photos
            OnIdentityInfoChanged?.Invoke(profile.Species, profile.Citizenship, profile.Employer, profile.Age, profile.Gender);
    }

    private void PopulateSpeciesSelector(string selectedSpecies, bool showPlaceholder)
    {
        SpeciesButton.Clear();
        for (var i = 0; i < _species.Count; i++)
        {
            SpeciesButton.AddItem(Loc.GetString(_species[i].Name), i);
            if (_species[i].ID == selectedSpecies)
                SpeciesButton.SelectId(i);
        }

        if (showPlaceholder)
            ApplyOptionButtonPlaceholder(SpeciesButton, Loc.GetString("generic-not-available-shorthand"));
    }

    private void PopulateCitizenshipSelector(HumanoidCharacterProfile profile, bool showPlaceholder)
    {
        CitizenshipButton.Clear();
        _citizenships.Clear();
        _citizenships.AddRange(GetAvailableCitizenships());
        for (var i = 0; i < _citizenships.Count; i++)
        {
            CitizenshipButton.AddItem(Loc.GetString(_citizenships[i].NameKey), i);
            if (_citizenships[i].ID == profile.Citizenship)
                CitizenshipButton.SelectId(i);
        }

        if (showPlaceholder || !_citizenships.Any(citizenship => citizenship.ID == profile.Citizenship))
            ApplyOptionButtonPlaceholder(CitizenshipButton, Loc.GetString("generic-not-available-shorthand"));
    }

    private void PopulateEmployerSelector(HumanoidCharacterProfile profile, bool showPlaceholder)
    {
        EmployerButton.Clear();
        _employers.Clear();
        _employers.AddRange(GetAvailableEmployers());
        for (var i = 0; i < _employers.Count; i++)
        {
            EmployerButton.AddItem(Loc.GetString(_employers[i].NameKey), i);
            if (_employers[i].ID == profile.Employer)
                EmployerButton.SelectId(i);
        }

        if (showPlaceholder || !_employers.Any(employer => employer.ID == profile.Employer))
            ApplyOptionButtonPlaceholder(EmployerButton, Loc.GetString("generic-not-available-shorthand"));
    }

    private List<CitizenshipPrototype> GetAvailableCitizenships()
    {
        return _proto.EnumeratePrototypes<CitizenshipPrototype>()
            .OrderBy(citizenship => Loc.GetString(citizenship.NameKey))
            .ToList();
    }

    private List<EmployerPrototype> GetAvailableEmployers()
    {
        return _proto.EnumeratePrototypes<EmployerPrototype>()
            .OrderBy(employer => Loc.GetString(employer.NameKey))
            .ToList();
    }

    private void CommitAgeEdit(string text)
    {
        if (_suppressEvents || _recordProfile == null)
            return;

        if (!int.TryParse(text, out var age))
        {
            UpdateRecordIdentityProfile(_recordProfile, false);
            return;
        }

        UpdateRecordIdentityProfile(_recordProfile.WithAge(age), true);
    }

    private void CommitForensicsEdits(string fingerprint, string dna)
    {
        if (_suppressEvents)
            return;

        OnForensicsInfoChanged?.Invoke(fingerprint, dna);
    }

    private static bool IsIdentitySelectorBlank(string? value)
    {
        // Pirate: records photos
        return string.IsNullOrWhiteSpace(value);
    }

    private static void ApplyOptionButtonPlaceholder(OptionButton button, string placeholder)
    {
        OptionButtonHelpers.SetPlaceholder(button, placeholder);
    }
    #endregion
}
