// SPDX-FileCopyrightText: 2025 Starlight
// SPDX-FileCopyrightText: 2026 SpaceStationUA
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.Character.Info.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterInspectWindow : FancyWindow
{
    public CharacterInspectWindow()
    {
        RobustXamlLoader.Load(this);
        InspectTabs.SetTabTitle(0, Loc.GetString("character-info-ic"));
        InspectTabs.SetTabTitle(1, Loc.GetString("character-info-ooc"));
        OnClose += ClearCharacter;
    }

    public void SetCharacter(EntityUid? target, IEntityManager entityManager, EntityUid viewer)
    {
        ICInfo.SetCharacter(target, entityManager, viewer);
        OOCInfo.SetCharacter(target, entityManager, viewer);
    }

    public void ClearCharacter()
    {
        ICInfo.ClearCharacter();
        OOCInfo.ClearCharacter();
    }
}
