// SPDX-FileCopyrightText: 2025 Starlight
// SPDX-FileCopyrightText: 2026 SpaceStationUA
// SPDX-License-Identifier: MIT

using Content.Shared._Pirate.Character.Info;
using Content.Shared._Pirate.Character.Info.Components;
using Content.Shared.Mind;
using Content.Shared.Roles.Jobs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Pirate.Character.Info.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterICInfoControl : Control
{
    public CharacterICInfoControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetCharacter(EntityUid? target, IEntityManager entityManager, EntityUid viewer)
    {
        if (target == null)
        {
            ClearCharacter();
            return;
        }

        var mindSystem = entityManager.System<SharedMindSystem>();
        var mind = mindSystem.GetMind(target.Value);
        CharacterView.SetCharacter(
            target,
            entityManager.System<SharedJobSystem>().MindTryGetJobName(mind, out var jobName)
                ? jobName
                : string.Empty,
            viewer);

        var characterInfo = entityManager.System<PirateSharedCharacterInfoSystem>();
        var description = characterInfo.GetPublicDescription(target.Value);
        DescriptionSection.Visible = !string.IsNullOrEmpty(description);
        CharacterDescription.SetMessage(FormattedMessage.RemoveMarkupPermissive(description));

        string? exploitable = null;
        if (characterInfo.CanAccessExploitableData(target.Value, viewer)
            && entityManager.TryGetComponent(target.Value, out ExploitableInfoComponent? exploitableComponent)
            && !string.IsNullOrEmpty(exploitableComponent.Info))
        {
            exploitable = exploitableComponent.Info;
        }

        ExploitableSection.Visible = exploitable != null;
        ExploitableInfo.SetMessage(FormattedMessage.RemoveMarkupPermissive(exploitable ?? string.Empty));

        string? secrets = null;
        if (characterInfo.CanAccessSecretData(target.Value, viewer)
            && entityManager.TryGetComponent(target.Value, out CharacterSecretsComponent? secretsComponent)
            && !string.IsNullOrEmpty(secretsComponent.Secrets))
        {
            secrets = secretsComponent.Secrets;
        }

        SecretsSection.Visible = secrets != null;
        SecretsInfo.SetMessage(FormattedMessage.RemoveMarkupPermissive(secrets ?? string.Empty));
        HiddenInfoSection.Visible = ExploitableSection.Visible || SecretsSection.Visible;
        InvalidateMeasure();
    }

    public void ClearCharacter()
    {
        CharacterView.ClearCharacter();
        CharacterDescription.Text = null;
        ExploitableInfo.Text = null;
        SecretsInfo.Text = null;
        DescriptionSection.Visible = false;
        ExploitableSection.Visible = false;
        SecretsSection.Visible = false;
        HiddenInfoSection.Visible = false;
        InvalidateMeasure();
    }
}
