// SPDX-FileCopyrightText: 2025 Starlight
// SPDX-FileCopyrightText: 2026 SpaceStationUA
// SPDX-License-Identifier: MIT

using Content.Shared._Pirate.Character.Info.Components;
using Content.Shared.Mind;
using Content.Shared.Roles.Jobs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Pirate.Character.Info.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterOOCInfoControl : Control
{
    public CharacterOOCInfoControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetCharacter(EntityUid? target, IEntityManager entityManager, EntityUid viewer)
    {
        if (target == null)
        {
            ClearCharacter();
            return;
        }

        var mindSystem = entityManager.System<SharedMindSystem>();
        var mind = mindSystem.GetMind(target.Value);
        CharacterView.SetCharacter(
            target,
            entityManager.System<SharedJobSystem>().MindTryGetJobName(mind, out var jobName)
                ? jobName
                : string.Empty,
            viewer);

        string? oocNotes = null;
        if (mind != null
            && entityManager.TryGetComponent(mind.Value, out RoleplayInfoComponent? roleplayInfo)
            && !string.IsNullOrEmpty(roleplayInfo.OOCNotes))
        {
            oocNotes = roleplayInfo.OOCNotes;
        }

        OOCNotesSection.Visible = oocNotes != null;
        OOCNotes.SetMessage(FormattedMessage.RemoveMarkupPermissive(oocNotes ?? string.Empty));

        string? personalNotes = null;
        if (mind != null
            && entityManager.TryGetComponent(mind.Value, out MindSecretsComponent? mindSecrets)
            && !string.IsNullOrEmpty(mindSecrets.PersonalNotes))
        {
            personalNotes = mindSecrets.PersonalNotes;
        }

        HiddenInfoSection.Visible = personalNotes != null;
        PersonalNotes.SetMessage(FormattedMessage.RemoveMarkupPermissive(personalNotes ?? string.Empty));
        InvalidateMeasure();
    }

    public void ClearCharacter()
    {
        CharacterView.ClearCharacter();
        OOCNotes.Text = null;
        PersonalNotes.Text = null;
        OOCNotesSection.Visible = false;
        HiddenInfoSection.Visible = false;
        InvalidateMeasure();
    }
}
