using System.Linq;
using Content.Shared._Pirate.UkraineAlarm;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.UkraineAlarm;

[GenerateTypedNameReferences]
public sealed partial class UkraineAlarmRegionSelectWindow : DefaultWindow
{
    private UkraineAlarmRegion[] _regions = [];

    public event Action<string>? RegionSelected;

    public UkraineAlarmRegionSelectWindow()
    {
        RobustXamlLoader.Load(this);
        RegionSearch.OnTextChanged += _ => RebuildList();
    }

    public void SetRegions(UkraineAlarmRegion[] regions)
    {
        _regions = regions.OrderBy(region => region.Name).ToArray();
        RebuildList();
    }

    private void RebuildList()
    {
        RegionList.RemoveAllChildren();

        var search = RegionSearch.Text.Trim();
        foreach (var region in _regions)
        {
            if (search.Length > 0 && !region.Name.Contains(search, StringComparison.CurrentCultureIgnoreCase))
                continue;

            var button = new Button { Text = region.Name };
            button.OnPressed += _ =>
            {
                RegionSelected?.Invoke(region.Id);
                Close();
            };
            RegionList.AddChild(button);
        }
    }
}
