// SPDX-FileCopyrightText: 2025 Starlight
// SPDX-FileCopyrightText: 2026 SpaceStationUA
// SPDX-License-Identifier: MIT

using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.Character.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterViewControl : Control
{
    [Dependency] private readonly IEntityManager _entities = default!;

    public CharacterViewControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetCharacter(EntityUid? target, string? subText = null, EntityUid? viewer = null)
    {
        CharacterSpriteView.SetEntity(target);
        if (target == null)
        {
            ClearCharacter();
            return;
        }

        CharacterNameLabel.Text = Identity.Name(target.Value, _entities, viewer);
        CharacterSubText.Text = subText ?? string.Empty;
    }

    public void ClearCharacter()
    {
        CharacterSpriteView.SetEntity(null);
        CharacterNameLabel.Text = string.Empty;
        CharacterSubText.Text = string.Empty;
    }
}
