// SPDX-FileCopyrightText: 2026 SpaceStationUA
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Text;
using Content.Client.Administration.Managers;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared.Administration;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Network;

namespace Content.Client._Pirate.Administration.MentorHelp;

[GenerateTypedNameReferences]
public sealed partial class MentorHelpControl : Control
{
    [Dependency] private readonly IClientAdminManager _adminManager = default!;
    [Dependency] private readonly IClientConsoleHost _console = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private readonly MentorHelpUIController _controller;
    private PlayerInfo? _currentPlayer;
    private int _newPlayerThreshold;

    public MentorHelpControl(MentorHelpUIController controller)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _controller = controller;
        _cfg.OnValueChanged(CCVars.NewPlayerThreshold, val => _newPlayerThreshold = val, true);

        // Responder-only notes are withheld from the player.
        ResponderOnly.OnToggled += args => PlaySound.Disabled = args.Pressed;

        ChannelSelector.OnSelectionChanged += sel =>
        {
            _currentPlayer = sel;
            _controller.OnPlayerSelected(sel);
            UpdateButtons();
            ChannelSelector.PlayerListContainer.DirtyList();
        };

        ChannelSelector.OverrideText += (info, text) =>
        {
            var sb = new StringBuilder();

            if (info.Connected)
                sb.Append(info.ActiveThisRound ? '⚫' : '◐');
            else
                sb.Append(info.ActiveThisRound ? '⭘' : '·');

            sb.Append(' ');
            if (_controller.TryGetPanel(info.SessionId, out var panel) && panel.Unread > 0)
            {
                sb.Append(panel.Unread < 11 ? new Rune('➀' + (panel.Unread - 1)) : new Rune(0x2639));
                sb.Append(' ');
            }

            if (IsNewPlayer(info))
                sb.Append(new Rune(0x23F2));

            sb.AppendFormat("\"{0}\"", text);
            return sb.ToString();
        };

        ChannelSelector.Comparison = (a, b) =>
        {
            var aPanel = _controller.EnsurePanel(a.SessionId);
            var bPanel = _controller.EnsurePanel(b.SessionId);

            if (a.IsPinned != b.IsPinned)
                return a.IsPinned ? -1 : 1;

            var aUnread = aPanel.Unread > 0;
            var bUnread = bPanel.Unread > 0;
            if (aUnread != bUnread)
                return aUnread ? -1 : 1;

            var aRecent = a.ActiveThisRound && aPanel.LastMessage != DateTime.MinValue;
            var bRecent = b.ActiveThisRound && bPanel.LastMessage != DateTime.MinValue;
            if (aRecent != bRecent)
                return aRecent ? -1 : 1;

            if (a.Connected != b.Connected)
                return a.Connected ? -1 : 1;

            if (a.Connected && b.Connected)
            {
                if (a.ActiveThisRound != b.ActiveThisRound)
                    return a.ActiveThisRound ? -1 : 1;

                var aNew = IsNewPlayer(a);
                var bNew = IsNewPlayer(b);
                if (aNew != bNew)
                    return aNew ? -1 : 1;
            }

            return bPanel.LastMessage.CompareTo(aPanel.LastMessage);
        };

        Follow.OnPressed += _ =>
        {
            if (_currentPlayer?.NetEntity is { } entity)
                _console.ExecuteCommand($"follow \"{entity}\"");
        };

        _adminManager.AdminStatusUpdated += UpdateButtons;
        UpdateButtons();
    }

    private bool IsNewPlayer(PlayerInfo info)
    {
        if (_newPlayerThreshold <= 0 || info.OverallPlaytime is null && !info.Connected)
            return false;

        return info.OverallPlaytime is null || info.OverallPlaytime < TimeSpan.FromMinutes(_newPlayerThreshold);
    }

    private void UpdateButtons()
    {
        Follow.Visible = _adminManager.CanCommand("follow");
        Follow.Disabled = _currentPlayer?.NetEntity == null;
    }

    public void SelectChannel(NetUserId channel)
    {
        foreach (var info in ChannelSelector.PlayerInfo)
        {
            if (info.SessionId != channel)
                continue;

            var data = new PlayerListData(info);
            if (!ChannelSelector.PlayerListContainer.Data.Contains(data))
                ChannelSelector.StopFiltering();

            ChannelSelector.PopulateList();
            ChannelSelector.PlayerListContainer.Select(data);
            return;
        }
    }

    public void OnMessage()
    {
        ChannelSelector.PopulateList();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _adminManager.AdminStatusUpdated -= UpdateButtons;
    }
}
