// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Pirate.Shared.Backrooms;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Pirate.Client.Backrooms;

[GenerateTypedNameReferences]
public sealed partial class BackroomsPreySenseWindow : DefaultWindow
{
    public event Action<BackroomsPreySenseTarget>? TargetSelected;

    private string _filter = string.Empty;
    private List<BackroomsPreySenseTarget> _targets = new();

    public BackroomsPreySenseWindow()
    {
        RobustXamlLoader.Load(this);

        SearchLineEdit.OnTextChanged += args =>
        {
            _filter = args.Text ?? string.Empty;
            Populate();
        };

        Populate();
    }

    public void SetTargets(IEnumerable<BackroomsPreySenseTarget> targets)
    {
        _targets = targets.ToList();
        Populate();
    }

    private void Populate()
    {
        TargetsList.DisposeAllChildren();

        var filter = _filter.Trim();
        var view = string.IsNullOrWhiteSpace(filter)
            ? _targets
            : _targets.Where(t => t.DisplayName.Contains(filter, StringComparison.CurrentCultureIgnoreCase));

        var any = false;
        foreach (var target in view)
        {
            any = true;
            var captured = target;
            var button = new Button
            {
                Text = captured.DisplayName,
                HorizontalAlignment = HAlignment.Stretch,
                ClipText = true,
            };
            button.OnPressed += _ => TargetSelected?.Invoke(captured);
            TargetsList.AddChild(button);
        }

        if (!any)
        {
            TargetsList.AddChild(new Label
            {
                Text = Loc.GetString("backrooms-prey-sense-empty"),
                HorizontalAlignment = HAlignment.Center,
            });
        }
    }
}
