// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Pirate.Shared.Atmos.HFR;
using Content.Shared.Atmos;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Pirate.Client.Atmos.HFR.UI;

/// <summary>
///     Client-side UI used to view a Hyper-torus Fusion Reactor (HFR).
///     Layout mirrors the /tg/station Hypertorus tgui interface: switches,
///     recipe selection, dynamic gas lists, a log-scale temperature chart,
///     reactor status/control and output control.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HFRWindow : FancyWindow
{
    // --- Bar fill / track styles ---
    private static readonly Color HeaderBlue = Color.FromHex("#3B5998");
    private static readonly Color FillGreen = Color.FromHex("#4CAF50");
    private static readonly Color FillYellow = Color.FromHex("#FFC107");
    private static readonly Color FillBlue = Color.FromHex("#2196F3");
    private static readonly Color FillGray = Color.FromHex("#9E9E9E");

    // Gas display info: label + bar color (hues follow the /tg/ gas palette).
    // NOTE: plain ASCII subscripts (O2, CO2...) — the game font has no glyph for
    // the Unicode subscript digits (₂), which rendered as a broken box in-game.
    private static readonly Dictionary<Gas, (string Label, Color Color)> GasInfo = new()
    {
        [Gas.Oxygen] = ("O2", Color.FromHex("#007FFF")),
        [Gas.Nitrogen] = ("N2", Color.FromHex("#00FFFF")),
        [Gas.CarbonDioxide] = ("CO2", Color.FromHex("#A00505")),
        [Gas.Plasma] = ("Plasma", Color.FromHex("#C852CE")),
        [Gas.Tritium] = ("Tritium", Color.FromHex("#00CC00")),
        [Gas.WaterVapor] = ("H2O", Color.FromHex("#707070")),
        [Gas.Ammonia] = ("NH3", Color.FromHex("#B4F7FB")),
        [Gas.NitrousOxide] = ("N2O", Color.FromHex("#C3DB20")),
        [Gas.Frezon] = ("Freon", Color.FromHex("#1791B5")),
        [Gas.BZ] = ("BZ", Color.FromHex("#E72C7C")),
        [Gas.Healium] = ("Healium", Color.FromHex("#43FFC9")),
        [Gas.Nitrium] = ("Nitrium", Color.FromHex("#FFCF51")),
        [Gas.Pluoxium] = ("Pluoxium", Color.FromHex("#4ABDF5")),
        [Gas.HyperNoblium] = ("Hyper-nob", Color.FromHex("#00BFA5")),
        [Gas.AntiNoblium] = ("Antinoblium", Color.FromHex("#E53935")),
        [Gas.Hydrogen] = ("H2", Color.FromHex("#FFFFFF")),
        [Gas.Helium] = ("He", Color.FromHex("#FFFD54")),
        [Gas.ProtoNitrate] = ("Proto-Nitrate", Color.FromHex("#00E676")),
        [Gas.Zauker] = ("Zauker", Color.FromHex("#66BB6A")),
        [Gas.Miasma] = ("Miasma", Color.FromHex("#8BC34A")),
        [Gas.Halon] = ("Halon", Color.FromHex("#B388FF")),
    };

    /// <summary>Gases always shown in the moderator list, even when absent (per /tg/).</summary>
    private static readonly Gas[] StickyModeratorGases = [Gas.Plasma, Gas.BZ];

    /// <summary>Recipe names and tier outputs, matching HfrRecipes.</summary>
    private static readonly (string Name, string Outputs)[] RecipeInfo =
    [
        ("Plasma + Oxygen", "-> CO2 · Frezon · N2O · Pluoxium"),
        ("Tritium + Oxygen", "-> Helium · Plasma · BZ · Hyper-nob"),
        ("Hyper-Noblium + Tritium", "-> Anti-Noblium · Helium · Proto-Nitrate · Zauker · Healium · Miasma"),
        ("Hydrogen + Oxygen", "-> Helium · Plasma · BZ · Hyper-nob"),
        ("Hydrogen + Tritium", "-> Helium · Plasma · BZ · Hyper-nob"),
        ("Hyper-Noblium + Hydrogen", "-> Anti-Noblium · Helium · Proto-Nitrate · Zauker · Healium · Miasma"),
        ("Hyper-Noblium + Anti-Noblium", "-> Plasma · Proto-Nitrate · Nitrium · Miasma · ⚠ CRITICAL MELTDOWN"),
    ];

    // --- Moderator filter options (GasId: 0 = None, otherwise Gas + 1) ---
    private static readonly (string Label, int GasId)[] FilterGases =
    [
        ("Nothing", 0),
        ("O2", (int) Gas.Oxygen + 1),
        ("N2", (int) Gas.Nitrogen + 1),
        ("CO2", (int) Gas.CarbonDioxide + 1),
        ("Plasma", (int) Gas.Plasma + 1),
        ("H2O", (int) Gas.WaterVapor + 1),
        ("Hyper-nob", (int) Gas.HyperNoblium + 1),
        ("N2O", (int) Gas.NitrousOxide + 1),
        ("Tritium", (int) Gas.Tritium + 1),
        ("BZ", (int) Gas.BZ + 1),
        ("Pluoxium", (int) Gas.Pluoxium + 1),
        ("Freon", (int) Gas.Frezon + 1),
        ("Healium", (int) Gas.Healium + 1),
        ("Nitrium", (int) Gas.Nitrium + 1),
        ("Antinoblium", (int) Gas.AntiNoblium + 1),
        ("Hydrogen", (int) Gas.Hydrogen + 1),
        ("Helium", (int) Gas.Helium + 1),
        ("Proto-Nitrate", (int) Gas.ProtoNitrate + 1),
        ("Zauker", (int) Gas.Zauker + 1),
        ("Miasma", (int) Gas.Miasma + 1),
        ("Halon", (int) Gas.Halon + 1),
    ];

    private readonly StyleBoxFlat _headerStyle = new() { BackgroundColor = HeaderBlue };
    private readonly StyleBoxFlat _filterSelectedStyle = new()
    {
        BackgroundColor = Color.FromHex("#2E7D32"),
        BorderColor = FillGreen,
        BorderThickness = new Thickness(1),
    };
    private readonly StyleBoxFlat _recipeSelectedStyle = new()
    {
        BackgroundColor = Color.FromHex("#2E7D32"),
        BorderColor = FillGreen,
        BorderThickness = new Thickness(1),
    };

    private readonly List<(Button Button, int GasId)> _filterButtons = new();
    private readonly List<Button> _recipeButtons = new();

    private readonly HypertorusTempChart _tempChart = new();

    private Dictionary<Gas, float> _fusionGases = [];
    private Dictionary<Gas, float> _moderatorGases = [];
    private byte _currentRecipe;
    private float _powerLevel;

    /// <summary>
    ///     True while we are applying a state pushed by the server, so toggle echo
    ///     updates don't get relayed back (see <see cref="OnToggleChanged"/>).
    /// </summary>
    private bool _syncingUi;

    public event Action<bool>? OnStartPowerToggled;
    public event Action<bool>? OnStartCoolingToggled;
    public event Action<bool>? OnStartFuelInjectionToggled;
    public event Action<bool>? OnStartModeratorInjectionToggled;
    public event Action<int>? OnRecipeSelected;
    public event Action<float>? OnHeatingConductorChanged;
    public event Action<float>? OnMagneticConstrictorChanged;
    public event Action<float>? OnFuelInjectionChanged;
    public event Action<float>? OnCurrentDampenerChanged;
    public event Action<float>? OnModeratorInjectionChanged;
    public event Action<float>? OnModeratorFilteringRateChanged;
    public event Action<bool>? OnWasteRemovalToggled;
    public event Action<int>? OnModeratorFilterChanged;
    public event Action? OnEmergencyShutdown;

    public HFRWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Section header banners.
        SwitchesHeader.PanelOverride = _headerStyle;
        FusionGasesHeader.PanelOverride = _headerStyle;
        ModeratorGasesHeader.PanelOverride = _headerStyle;
        TempsHeader.PanelOverride = _headerStyle;
        StatusHeader.PanelOverride = _headerStyle;
        ControlHeader.PanelOverride = _headerStyle;
        OutputHeader.PanelOverride = _headerStyle;

        // Parameter bars (TG colors: outlined = colored border track, solid = filled).
        StyleBar(PowerLevelBar, FillGreen);
        StyleBar(IntegrityBar, FillGreen);
        StyleBar(IronContentBar, FillGreen);
        StyleBar(EnergyBar, FillYellow);
        StyleBar(HeatLimiterBar, FillBlue);
        StyleBar(HeatOutputBar, FillGray);

        // Temperature chart.
        TempChartHost.AddChild(_tempChart);

        // Recipe selection collapsible (as in the /tg/ interface).
        BuildRecipeCollapsible();

        // Switches. OnToggled fires both for user clicks and for programmatic state
        // syncs (server echoes). We only relay USER clicks to the server — echoing the
        // server's own state back would fight the click (toggle snaps back / never sticks).
        StartPowerToggle.OnToggled += args => OnToggleChanged(StartPowerToggle, args.Pressed, OnStartPowerToggled);
        StartCoolingToggle.OnToggled += args => OnToggleChanged(StartCoolingToggle, args.Pressed, OnStartCoolingToggled);
        FusionInjectionSwitch.OnToggled += args => OnToggleChanged(FusionInjectionSwitch, args.Pressed, OnStartFuelInjectionToggled);
        ModeratorInjectionSwitch.OnToggled += args => OnToggleChanged(ModeratorInjectionSwitch, args.Pressed, OnStartModeratorInjectionToggled);

        // Injection rates live next to their switches (per /tg/).
        FusionInjectionRateInput.OnTextEntered += args => OnFuelInjectionChanged?.Invoke(ParseFloat(args.Text));
        ModeratorInjectionRateInput.OnTextEntered += args => OnModeratorInjectionChanged?.Invoke(ParseFloat(args.Text));

        // Reactor control inputs.
        HeatingConductorInput.OnTextEntered += args => OnHeatingConductorChanged?.Invoke(ParseFloat(args.Text));
        MagneticConstrictorInput.OnTextEntered += args => OnMagneticConstrictorChanged?.Invoke(ParseFloat(args.Text));
        CurrentDampenerInput.OnTextEntered += args => OnCurrentDampenerChanged?.Invoke(ParseFloat(args.Text));

        // Output control.
        WasteRemovalToggle.OnToggled += args => OnToggleChanged(WasteRemovalToggle, args.Pressed, OnWasteRemovalToggled);
        ModeratorFilterRateInput.OnTextEntered += args => OnModeratorFilteringRateChanged?.Invoke(ParseFloat(args.Text));
        EmergencyShutdownButton.OnPressed += _ => OnEmergencyShutdown?.Invoke();

        // Moderator filter grid.
        foreach (var (label, gasId) in FilterGases)
        {
            var button = new Button
            {
                Text = label,
                MinWidth = 58,
                MinHeight = 26,
            };
            button.OnPressed += _ =>
            {
                SetFilterSelection(gasId);
                OnModeratorFilterChanged?.Invoke(gasId);
            };
            FilterGrid.AddChild(button);
            _filterButtons.Add((button, gasId));
        }
        SetFilterSelection(0);

        // "Show mix gases" toggle: dumps every gas in the fusion and moderator
        // mixes (name + moles), so the crew can see the full composition even for
        // gases that aren't sticky in the per-mix bars.
        ShowGasesButton.OnPressed += _ => ToggleGasReadout();
    }

    private void BuildRecipeCollapsible()
    {
        var body = new CollapsibleBody();
        var list = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 3,
            Margin = new Thickness(0, 6, 0, 0),
        };

        for (var i = 0; i < RecipeInfo.Length; i++)
        {
            var index = i;
            var (name, outputs) = RecipeInfo[i];

            var button = new Button { Text = name, StyleClasses = { "OpenBoth" }, HorizontalExpand = true };
            button.OnPressed += _ =>
            {
                if (_powerLevel > 0f)
                    return; // recipes can only be changed while the reactor is cold (per /tg/)
                OnRecipeSelected?.Invoke(index);
            };
            list.AddChild(button);
            list.AddChild(new Label
            {
                Text = outputs,
                FontColorOverride = Color.FromHex("#808080"),
            });
            _recipeButtons.Add(button);
        }

        body.AddChild(list);
        RecipeHost.AddChild(new Collapsible("Recipe selection", body));
    }

    /// <summary>
    ///     Applies an outlined (colored border) track + solid fill to a status bar.
    /// </summary>
    private static void StyleBar(ProgressBar bar, Color color)
    {
        bar.BackgroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(0.12f, 0.12f, 0.14f, 1f),
            BorderColor = color,
            BorderThickness = new Thickness(1),
        };
        bar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = color };
    }

    // --- State setters (called from HFRBoundUserInterface) ---

    public void SetTemperatures(float fusion, float moderator, float coolant, float output,
        float fusionDelta, float moderatorDelta, float coolantDelta, float outputDelta, float powerLevel)
    {
        _powerLevel = powerLevel;
        // PL6 "next level" marker = the fusion maximum scaled by the recipe's temperature multiplier.
        var recipe = HfrRecipes.All[Math.Clamp(_currentRecipe, 0, HfrRecipes.All.Length - 1)];
        var maxLevelTemp = recipe.MaxTemperatureModifier * HFRConstants.FusionMaxTemperature;
        _tempChart.UpdateData(
            [fusion, moderator, coolant, output],
            [fusionDelta, moderatorDelta, coolantDelta, outputDelta],
            powerLevel,
            maxLevelTemp);
        _tempChart.InvalidateMeasure();
    }

    public void SetGases(Dictionary<Gas, float> fusion, Dictionary<Gas, float> moderator)
    {
        _fusionGases = fusion;
        _moderatorGases = moderator;
        RebuildGasLists();
        if (GasReadoutPanel.Visible)
            RefreshGasReadout();
    }

    public void SetStatus(float powerLevel, float integrity, float ironContent, float heatOutput, float heatLimiter, float energy,
        bool meltdownActive = false, float meltdownCountdown = 0f)
    {
        MeltdownWarningLabel.Visible = meltdownActive;
        MeltdownWarningLabel.Text = meltdownActive
            ? Loc.GetString("hfr-meltdown-ui-warning", ("seconds", Math.Max(0, (int) Math.Ceiling(meltdownCountdown))))
            : string.Empty;

        SetBar(PowerLevelBar, PowerLevelValue, powerLevel, 6f, $"{powerLevel:0}");
        SetBar(IntegrityBar, IntegrityValue, integrity, 100f, $"{integrity:F1}%");
        // Iron content can accumulate up to 300% (server clamp), so the bar must
        // span 300 too — otherwise it reads full while the value keeps climbing.
        SetBar(IronContentBar, IronContentValue, ironContent, 300f, $"{ironContent:F1}%");
        // E=mc² energy is astronomically large (c² ≈ 9e16). For display we strip the
        // light-speed amplifier AND the recipe's energy divisor, leaving the readable
        // "energy level" = energyModifiers * max(T*heatModifier/100, 1) in J/kJ/MJ —
        // nonzero whenever the fusion mix is healthy and growing with temperature.
        var recipe = HfrRecipes.All[Math.Clamp(_currentRecipe, 0, HfrRecipes.All.Length - 1)];
        var displayEnergy = energy / (HFRConstants.LightSpeed * HFRConstants.LightSpeed) * recipe.EnergyModifier;
        SetBar(EnergyBar, EnergyValue, displayEnergy, AutoScale(displayEnergy),
            FormatNumber(displayEnergy, "J"));
        SetBar(HeatLimiterBar, HeatLimiterValue, heatLimiter, AutoScale(heatLimiter), FormatNumber(heatLimiter, "K"));
        // Heat output shown as a percentage of the limiter cap — the meaningful
        // comparison (per /tg/: reaching the cap means max reaction rate).
        var heatPct = heatLimiter > 0f ? heatOutput / heatLimiter * 100f : 0f;
        SetBar(HeatOutputBar, HeatOutputValue, MathF.Abs(heatPct), 100f,
            $"{heatPct:+#.##;-#.##;0}%");
    }

    /// <summary>
    ///     Switch states with the /tg/ interlock rules: the reactor cannot be powered
    ///     down while hot, cooling is locked while injection runs, and injection needs power+cooling.
    /// </summary>
    public void SetSwitches(bool power, bool cooling, bool fuel, bool moderator, float powerLevel)
    {
        var running = powerLevel > 0f;

        StartPowerToggle.Disabled = running;
        StartCoolingToggle.Disabled = fuel || moderator || !power || (cooling && running);
        FusionInjectionSwitch.Disabled = !power || !cooling;
        ModeratorInjectionSwitch.Disabled = !power || !cooling;

        _syncingUi = true;
        SetToggleState(StartPowerToggle, power);
        SetToggleState(StartCoolingToggle, cooling);
        SetToggleState(FusionInjectionSwitch, fuel);
        SetToggleState(ModeratorInjectionSwitch, moderator);
        _syncingUi = false;
    }

    public void SetWasteRemoval(bool on)
    {
        _syncingUi = true;
        SetToggleState(WasteRemovalToggle, on);
        _syncingUi = false;
    }

    public void SetTweakables(float heatingConductor, float magneticConstrictor, float fuelRate,
        float moderatorRate, float currentDamper, float filteringRate)
    {
        SetInput(HeatingConductorInput, heatingConductor);
        SetInput(MagneticConstrictorInput, magneticConstrictor);
        SetInput(FusionInjectionRateInput, fuelRate);
        SetInput(ModeratorInjectionRateInput, moderatorRate);
        SetInput(CurrentDampenerInput, currentDamper);
        SetInput(ModeratorFilterRateInput, filteringRate);
    }

    public void SetFilterSelection(int gasId)
    {
        foreach (var (button, id) in _filterButtons)
            button.StyleBoxOverride = id == gasId ? _filterSelectedStyle : null;
    }

    public void SetRecipe(byte recipe)
    {
        _currentRecipe = recipe;
        for (var i = 0; i < _recipeButtons.Count; i++)
        {
            _recipeButtons[i].StyleBoxOverride = i == recipe ? _recipeSelectedStyle : null;
            _recipeButtons[i].Disabled = _powerLevel > 0f; // recipes lock while the reactor runs
        }

        RebuildGasLists(); // refresh fusion sticky gases for the selected recipe
    }

    public void SetOutputStatus(string status)
    {
        OutputStatusLabel.Text = status;
    }

    /// <summary>
    ///     Toggles the full gas readout panel and refreshes its contents from the
    ///     last received fusion/moderator gas dictionaries.
    /// </summary>
    private void ToggleGasReadout()
    {
        var show = !GasReadoutPanel.Visible;
        GasReadoutPanel.Visible = show;
        ShowGasesButton.Text = show ? "Hide mix gases" : "Show mix gases";
        if (show)
            RefreshGasReadout();
    }

    private void RefreshGasReadout()
    {
        FusionReadoutLabel.SetMessage(BuildGasReadout(_fusionGases, "No fuel gases present"));
        ModeratorReadoutLabel.SetMessage(BuildGasReadout(_moderatorGases, "No moderator gases present"));
    }

    /// <summary>
    ///     Builds a multi-line readout of every gas in the mix, sorted by moles
    ///     descending, using the same labels/colors as the per-gas bars.
    /// </summary>
    private static FormattedMessage BuildGasReadout(IReadOnlyDictionary<Gas, float> gases, string emptyText)
    {
        var msg = new FormattedMessage();
        var items = gases.OrderByDescending(kv => kv.Value).ToList();
        if (items.Count == 0)
        {
            msg.AddText(emptyText);
            return msg;
        }

        for (var i = 0; i < items.Count; i++)
        {
            var (gas, moles) = items[i];
            var label = GasInfo.TryGetValue(gas, out var info) ? info.Label : gas.ToString();
            var color = GasInfo.TryGetValue(gas, out var info2) ? info2.Color : Color.White;
            msg.PushColor(color);
            msg.AddText($"{label}: ");
            msg.Pop();
            msg.AddText($"{moles:F2} mol");
            if (i < items.Count - 1)
                msg.AddText("\n");
        }

        return msg;
    }

    // --- Internals ---

    private void SetToggleState(Button button, bool on)
    {
        button.Pressed = on;
        button.Text = on ? "On" : "Off";
    }

    /// <summary>
    ///     Shared handler for the toggle buttons. Updates the On/Off label immediately
    ///     (optimistic UI) and only relays the change to the server when it came from a
    ///     user click. Programmatic state syncs (server echoes) must not re-send:
    ///     setting <see cref="Button.Pressed"/> fires OnToggled again, so an echo that
    ///     arrives after the click would otherwise overwrite the player's choice.
    /// </summary>
    private void OnToggleChanged(Button button, bool pressed, Action<bool>? send)
    {
        if (_syncingUi)
            return;

        button.Text = pressed ? "On" : "Off";
        send?.Invoke(pressed);
    }

    // Mole-bar scale caps: fusion bars fill at 1000 moles, moderator bars at 500
    // (per /tg/ moderator scale). Values above the cap are clamped so both the bar
    // and the readout stop at a readable maximum instead of "flying into space".
    private const float FusionBarMaxMoles = 1000f;
    private const float ModeratorBarMaxMoles = 500f;

    private void RebuildGasLists()
    {
        // Fusion: sticky gases = the selected recipe's fuel requirements.
        var recipe = HfrRecipes.All[Math.Clamp(_currentRecipe, 0, HfrRecipes.All.Length - 1)];
        RebuildGasList(FusionGasList, _fusionGases, [recipe.PrimaryFuel, recipe.SecondaryFuel], FusionBarMaxMoles);
        RebuildGasList(ModeratorGasList, _moderatorGases, StickyModeratorGases, ModeratorBarMaxMoles);
    }

    private static void RebuildGasList(BoxContainer list, IReadOnlyDictionary<Gas, float> gases, IReadOnlyList<Gas> sticky, float maxScale)
    {
        list.RemoveAllChildren();

        var items = gases.OrderByDescending(kv => kv.Value).ToList();
        foreach (var gas in sticky)
        {
            if (!items.Any(i => i.Key == gas))
                items.Add(new KeyValuePair<Gas, float>(gas, 0f));
        }

        foreach (var (gas, moles) in items)
        {
            if (!GasInfo.TryGetValue(gas, out var info))
                continue;

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 5,
            };
            row.AddChild(new Label
            {
                Text = info.Label + ":",
                SetWidth = 92,
                VerticalAlignment = Control.VAlignment.Center,
            });

            // Bar fills relative to the scale cap; the displayed number is clamped
            // to the same cap so it never outgrows the bar's meaning.
            var displayMoles = Math.Min(moles, maxScale);
            var bar = new ProgressBar
            {
                HorizontalExpand = true,
                SetHeight = 14,
                VerticalAlignment = Control.VAlignment.Center,
                MaxValue = maxScale,
                Value = displayMoles,
                ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = info.Color },
                BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = new Color(0.12f, 0.12f, 0.14f, 1f) },
            };
            row.AddChild(bar);

            // Wide enough that "1000.00 moles" never spills back over the bar.
            row.AddChild(new Label
            {
                Text = $"{displayMoles:F2} moles",
                Align = Label.AlignMode.Right,
                SetWidth = 105,
                VerticalAlignment = Control.VAlignment.Center,
            });

            list.AddChild(row);
        }
    }

    private static void SetBar(ProgressBar bar, Label label, float value, float max, string text)
    {
        label.Text = text;
        bar.MaxValue = Math.Max(max, 1f);
        bar.Value = Math.Clamp(value, 0f, bar.MaxValue);
    }

    private static void SetInput(LineEdit input, float value)
    {
        if (!input.HasKeyboardFocus())
            input.Text = value.ToString("0.##", CultureInfo.InvariantCulture);
    }

    private static float AutoScale(float value)
    {
        return Math.Max(value * 1.2f, 1f);
    }

    private static readonly (float Divisor, string Suffix)[] NumberPrefixes =
    [
        (1e30f, "Q"), (1e27f, "R"), (1e24f, "Y"), (1e21f, "Z"), (1e18f, "E"),
        (1e15f, "P"), (1e12f, "T"), (1e9f, "G"), (1e6f, "M"), (1e3f, "k"),
    ];

    /// <summary>
    ///     Formats a status value with SI prefixes (k/M/G/T/P/E/Z/Y/R/Q) so the huge
    ///     E=mc² energy and heat figures stay readable, e.g. "10 EJ" or "5 MK".
    /// </summary>
    private static string FormatNumber(float value, string unit)
    {
        var abs = MathF.Abs(value);
        if (abs < 1e3f)
            return $"{value:0.##}{unit}";

        // Pick the largest prefix that keeps the displayed value below 1000
        // (so even the energy clamp 1e35 renders as "100 QJ", not "100000QJ").
        foreach (var (divisor, suffix) in NumberPrefixes)
        {
            if (abs >= divisor)
                return $"{value / divisor:0.##}{suffix}{unit}";
        }

        return $"{value:0.##}{unit}";
    }

    private static float ParseFloat(string text)
    {
        return float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out var result) ? result : 0f;
    }
}

/// <summary>
///     Log-scale vertical bar chart for the four HFR temperatures, mirroring the
///     /tg/ "Gas Monitoring" widget: unified temperature axis with power-level
///     markers, per-gas bars and rate-of-change (K/s) readouts.
/// </summary>
public sealed class HypertorusTempChart : Control
{
    private const float ChartHeight = 200f;
    private const float ChartWidth = 320f;
    private const float AxisWidth = 84f;

    private static readonly Color Bg = new(0.09f, 0.09f, 0.12f, 1f);
    private static readonly Color TickColor = new(0.32f, 0.32f, 0.38f, 1f);
    private static readonly Color LabelColor = new(0.72f, 0.72f, 0.78f, 1f);
    private static readonly Color EmptyColor = Color.FromHex("#f44336");

    private static readonly (string Name, Color Color)[] Series =
    [
        ("Fusion", Color.FromHex("#f2711c")),
        ("Moderator", Color.FromHex("#e03997")),
        ("Coolant", Color.FromHex("#f0f8ff")),
        ("Output", Color.FromHex("#20b142")),
    ];

    private readonly Font _font;
    private readonly float[] _values = new float[4];
    private readonly float[] _deltas = new float[4];
    private float _powerLevel;
    private float _maxLevelTemp = HFRConstants.FusionMaxTemperature;

    public HypertorusTempChart()
    {
        _font = new VectorFont(
            IoCManager.Resolve<IResourceCache>().GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Regular.ttf"),
            11);
        HorizontalExpand = true;
        VerticalExpand = true;
        MinSize = new Vector2(AxisWidth + ChartWidth + 8f, ChartHeight + 64f);
    }

    public void UpdateData(float[] values, float[] deltas, float powerLevel, float maxLevelTemp)
    {
        Array.Copy(values, _values, Math.Min(values.Length, _values.Length));
        Array.Copy(deltas, _deltas, Math.Min(deltas.Length, _deltas.Length));
        _powerLevel = powerLevel;
        _maxLevelTemp = maxLevelTemp;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        var scale = UIScale;

        // Fill the full control size, not a fixed rectangle.
        var chartWidth = MathF.Max(ChartWidth, Size.X - AxisWidth - 8f);
        var chartHeight = MathF.Max(ChartHeight, Size.Y - 64f);
        var totalWidth = AxisWidth + chartWidth + 8f;

        // Background.
        handle.DrawRect(UIBox2.FromDimensions(Vector2.Zero, new Vector2(totalWidth, chartHeight) * scale), Bg);

        // Log-scale bounds (single pass, no allocation).
        var minPositive = float.MaxValue;
        var maxTemp = 1000f;
        foreach (var v in _values)
        {
            if (v <= 0f)
                continue;
            if (v < minPositive)
                minPositive = v;
            if (v > maxTemp)
                maxTemp = v;
        }

        // Everything above 20 K starts the axis at 20 (so a hot reactor doesn't
        // compress the scale with a 2.7 K floor); otherwise clamp to [2.73, 20].
        var minTemp = minPositive == float.MaxValue
            ? 2.73f
            : Math.Clamp(minPositive, 2.73f, 20f);

        var prevLevel = 0f;
        var nextLevel = 0f;
        switch ((int) _powerLevel)
        {
            case 0: nextLevel = 500f; break;
            case 1: prevLevel = 500f; nextLevel = 1000f; break;
            case 2: prevLevel = 1000f; nextLevel = 10000f; break;
            case 3: prevLevel = 10000f; nextLevel = 100000f; break;
            case 4: prevLevel = 100000f; nextLevel = 1000000f; break;
            case 5: prevLevel = 1000000f; nextLevel = 10000000f; break;
            default: prevLevel = 10000000f; nextLevel = _maxLevelTemp; break;
        }

        maxTemp = Math.Max(maxTemp, Math.Max(prevLevel, nextLevel));
        if (maxTemp <= minTemp)
            maxTemp = minTemp * 2f;

        float Ratio(float v)
        {
            if (v <= 0f)
                return 0f;
            var r = (MathF.Log10(v) - MathF.Log10(minTemp))
                / (MathF.Log10(maxTemp) - MathF.Log10(minTemp));
            return Math.Clamp(r, 0f, 1f);
        }

        // Y-axis ticks at the power level boundaries.
        DrawTick(handle, scale, minTemp, Ratio, chartWidth, chartHeight, LabelColor);
        if (prevLevel > 0f)
            DrawTick(handle, scale, prevLevel, Ratio, chartWidth, chartHeight, LabelColor);
        DrawTick(handle, scale, nextLevel, Ratio, chartWidth, chartHeight, LabelColor);
        DrawTick(handle, scale, maxTemp, Ratio, chartWidth, chartHeight, LabelColor);

        // Bars + legend, spaced evenly across the full chart width.
        var barSpacing = (chartWidth - 44f) / 4f;
        for (var i = 0; i < Series.Length; i++)
        {
            var barX = AxisWidth + 22f + i * barSpacing;
            var centerX = barX + 7f;
            var value = _values[i];

            if (value > 0f)
            {
                var height = chartHeight * Ratio(value);
                handle.DrawRect(
                    UIBox2.FromDimensions(
                        new Vector2(barX, chartHeight - height) * scale,
                        new Vector2(14f, height) * scale),
                    Series[i].Color);
            }

            // Legend: name / value / delta under each bar.
            DrawCentered(handle, scale, centerX, chartHeight + 4f, Series[i].Name, LabelColor);
            if (value > 0f)
            {
                DrawCentered(handle, scale, centerX, chartHeight + 19f, FormatTemp(value), Color.White);
                var delta = _deltas[i];
                var deltaText = delta == 0f
                    ? "-"
                    : $"{(delta > 0f ? "+" : "")}{FormatTemp(delta)} K/s";
                DrawCentered(handle, scale, centerX, chartHeight + 34f, deltaText, LabelColor);
            }
            else
            {
                DrawCentered(handle, scale, centerX, chartHeight + 19f, "Empty", EmptyColor);
            }
        }
    }

    private void DrawTick(DrawingHandleScreen handle, float scale, float value, Func<float, float> ratio, float chartWidth, float chartHeight, Color color)
    {
        var y = (chartHeight - ratio(value) * chartHeight) * scale;
        handle.DrawRect(
            UIBox2.FromDimensions(new Vector2(AxisWidth * scale, y), new Vector2(chartWidth * scale, 1f)),
            TickColor);

        var text = FormatTemp(value);
        var dims = handle.GetDimensions(_font, text, scale);
        handle.DrawString(_font, new Vector2((AxisWidth - 4f) * scale - dims.X, y - dims.Y / 2f), text, scale, color);
    }

    private void DrawCentered(DrawingHandleScreen handle, float scale, float centerX, float topY, string text, Color color)
    {
        var dims = handle.GetDimensions(_font, text, scale);
        handle.DrawString(
            _font,
            new Vector2(centerX * scale - dims.X / 2f, topY * scale),
            text,
            scale,
            color);
    }

    private static string FormatTemp(float value)
    {
        var abs = MathF.Abs(value);
        if (abs >= 1e6f)
            return $"{value / 1e6f:0.##}M";
        if (abs >= 1e3f)
            return $"{value / 1e3f:0.##}k";
        return MathF.Round(value).ToString(CultureInfo.InvariantCulture);
    }
}
